// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_submodule.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {
void define_algebra(jlcxx::Module &mod) {
  using namespace xdiag;
  mod.method("fun_symmetrize", [](Op const &op, PermutationGroup const &group) {
    JULIA_XDIAG_CALL_RETURN(symmetrize(op, group))
  });
  mod.method("fun_symmetrize", [](Op const &op, Representation const &irrep) {
    JULIA_XDIAG_CALL_RETURN(symmetrize(op, irrep))
  });
  mod.method("fun_symmetrize",
             [](OpSum const &ops, PermutationGroup const &group) {
               JULIA_XDIAG_CALL_RETURN(symmetrize(ops, group))
             });
  mod.method("fun_symmetrize",
             [](OpSum const &ops, Representation const &irrep) {
               JULIA_XDIAG_CALL_RETURN(symmetrize(ops, irrep))
             });

  // operator overloads
}
} // namespace xdiag::julia
