// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_submodule.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {
void define_blocks(jlcxx::Module &mod) {
  using namespace xdiag;
  mod.method("fun_dim",
             [](Fermion const &block) { JULIA_XDIAG_CALL_RETURN(dim(block)) });
  mod.method("fun_dim",
             [](Boson const &block) { JULIA_XDIAG_CALL_RETURN(dim(block)) });
  mod.method("fun_dim",
             [](Spinhalf const &block) { JULIA_XDIAG_CALL_RETURN(dim(block)) });
  mod.method("fun_dim",
             [](Electron const &block) { JULIA_XDIAG_CALL_RETURN(dim(block)) });
  mod.method("fun_dim",
             [](tJ const &block) { JULIA_XDIAG_CALL_RETURN(dim(block)) });
  mod.method("fun_size",
             [](Fermion const &block) { JULIA_XDIAG_CALL_RETURN(size(block)) });
  mod.method("fun_size",
             [](Boson const &block) { JULIA_XDIAG_CALL_RETURN(size(block)) });
  mod.method("fun_size", [](Spinhalf const &block) {
    JULIA_XDIAG_CALL_RETURN(size(block))
  });
  mod.method("fun_size", [](Electron const &block) {
    JULIA_XDIAG_CALL_RETURN(size(block))
  });
  mod.method("fun_size",
             [](tJ const &block) { JULIA_XDIAG_CALL_RETURN(size(block)) });
  mod.method("fun_nsites", [](Fermion const &block) {
    JULIA_XDIAG_CALL_RETURN(nsites(block))
  });
  mod.method("fun_nsites",
             [](Boson const &block) { JULIA_XDIAG_CALL_RETURN(nsites(block)) });
  mod.method("fun_nsites", [](Spinhalf const &block) {
    JULIA_XDIAG_CALL_RETURN(nsites(block))
  });
  mod.method("fun_nsites", [](Electron const &block) {
    JULIA_XDIAG_CALL_RETURN(nsites(block))
  });
  mod.method("fun_nsites",
             [](tJ const &block) { JULIA_XDIAG_CALL_RETURN(nsites(block)) });
  mod.method("fun_isreal", [](Fermion const &block) {
    JULIA_XDIAG_CALL_RETURN(isreal(block))
  });
  mod.method("fun_isreal",
             [](Boson const &block) { JULIA_XDIAG_CALL_RETURN(isreal(block)) });
  mod.method("fun_isreal", [](Spinhalf const &block) {
    JULIA_XDIAG_CALL_RETURN(isreal(block))
  });
  mod.method("fun_isreal", [](Electron const &block) {
    JULIA_XDIAG_CALL_RETURN(isreal(block))
  });
  mod.method("fun_isreal",
             [](tJ const &block) { JULIA_XDIAG_CALL_RETURN(isreal(block)) });
  mod.method("fun_index", [](Fermion const &block, ProductState const &pstate) {
    JULIA_XDIAG_CALL_RETURN(index(block, pstate))
  });
  mod.method("fun_index", [](Boson const &block, ProductState const &pstate) {
    JULIA_XDIAG_CALL_RETURN(index(block, pstate))
  });
  mod.method("fun_index",
             [](Spinhalf const &block, ProductState const &pstate) {
               JULIA_XDIAG_CALL_RETURN(index(block, pstate))
             });
  mod.method("fun_index",
             [](Electron const &block, ProductState const &pstate) {
               JULIA_XDIAG_CALL_RETURN(index(block, pstate))
             });
  mod.method("fun_index", [](tJ const &block, ProductState const &pstate) {
    JULIA_XDIAG_CALL_RETURN(index(block, pstate))
  });
  mod.method("fun_to_string", [](Fermion const &block) {
    JULIA_XDIAG_CALL_RETURN(to_string(block))
  });
  mod.method("fun_to_string", [](Boson const &block) {
    JULIA_XDIAG_CALL_RETURN(to_string(block))
  });
  mod.method("fun_to_string", [](Spinhalf const &block) {
    JULIA_XDIAG_CALL_RETURN(to_string(block))
  });
  mod.method("fun_to_string", [](Electron const &block) {
    JULIA_XDIAG_CALL_RETURN(to_string(block))
  });
  mod.method("fun_to_string",
             [](tJ const &block) { JULIA_XDIAG_CALL_RETURN(to_string(block)) });
  mod.method("fun_to_string",
             [](ProductState const &state, Fermion const &block) {
               JULIA_XDIAG_CALL_RETURN(to_string(state, block))
             });
  mod.method("fun_to_string",
             [](ProductState const &state, Boson const &block) {
               JULIA_XDIAG_CALL_RETURN(to_string(state, block))
             });
  mod.method("fun_to_string",
             [](ProductState const &state, Spinhalf const &block) {
               JULIA_XDIAG_CALL_RETURN(to_string(state, block))
             });
  mod.method("fun_to_string",
             [](ProductState const &state, Electron const &block) {
               JULIA_XDIAG_CALL_RETURN(to_string(state, block))
             });
  mod.method("fun_to_string", [](ProductState const &state, tJ const &block) {
    JULIA_XDIAG_CALL_RETURN(to_string(state, block))
  });
  mod.method("fun_isapprox",
             [](Fermion const &b1, Fermion const &b2, double tol = 1e-12) {
               JULIA_XDIAG_CALL_RETURN(isapprox(b1, b2, 1e-12))
             });
  mod.method("fun_isapprox",
             [](Boson const &b1, Boson const &b2, double tol = 1e-12) {
               JULIA_XDIAG_CALL_RETURN(isapprox(b1, b2, 1e-12))
             });
  mod.method("fun_isapprox",
             [](Spinhalf const &b1, Spinhalf const &b2, double tol = 1e-12) {
               JULIA_XDIAG_CALL_RETURN(isapprox(b1, b2, 1e-12))
             });
  mod.method("fun_isapprox",
             [](Electron const &b1, Electron const &b2, double tol = 1e-12) {
               JULIA_XDIAG_CALL_RETURN(isapprox(b1, b2, 1e-12))
             });
  mod.method("fun_isapprox",
             [](tJ const &b1, tJ const &b2, double tol = 1e-12) {
               JULIA_XDIAG_CALL_RETURN(isapprox(b1, b2, 1e-12))
             });
  mod.method("con_Boson", []() { JULIA_XDIAG_CALL_RETURN(Boson()) });
  mod.method("con_Boson", [](int64_t sites, int64_t d) {
    JULIA_XDIAG_CALL_RETURN(Boson(sites, d))
  });
  mod.method("con_Boson", [](int64_t sites, int64_t d, int64_t number) {
    JULIA_XDIAG_CALL_RETURN(Boson(sites, d, number))
  });
  mod.method("con_Boson",
             [](int64_t sites, int64_t d, Representation const &irrep) {
               JULIA_XDIAG_CALL_RETURN(Boson(sites, d, irrep))
             });
  mod.method("con_Boson", [](int64_t sites, int64_t d, int64_t number,
                             Representation const &irrep) {
    JULIA_XDIAG_CALL_RETURN(Boson(sites, d, number, irrep))
  });
  mod.method("mth_nsites",
             [](const Boson &self) { JULIA_XDIAG_CALL_RETURN(self.nsites()) });
  mod.method("mth_d",
             [](const Boson &self) { JULIA_XDIAG_CALL_RETURN(self.d()) });
  mod.method("mth_dim",
             [](const Boson &self) { JULIA_XDIAG_CALL_RETURN(self.dim()) });
  mod.method("mth_size",
             [](const Boson &self) { JULIA_XDIAG_CALL_RETURN(self.size()) });
  mod.method("mth_isreal",
             [](const Boson &self) { JULIA_XDIAG_CALL_RETURN(self.isreal()) });
  mod.method("mth_index", [](Boson const &self, ProductState const &pstate) {
    JULIA_XDIAG_CALL_RETURN(self.index(pstate))
  });
  mod.method("mth_operator==", [](Boson const &self, Boson const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
  });
  mod.method("mth_operator!=", [](Boson const &self, Boson const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator!=(rhs))
  });
  mod.method("con_BosonIterator", [](Boson const *block, int64_t idx) {
    JULIA_XDIAG_CALL_RETURN(BosonIterator(block, idx))
  });
  mod.method("mth_operator*", [](const BosonIterator &self) {
    JULIA_XDIAG_CALL_RETURN(self.operator*())
  });
  mod.method("mth_operator==",
             [](BosonIterator const &self, BosonIterator const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
             });
  mod.method("mth_operator!=",
             [](BosonIterator const &self, BosonIterator const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator!=(rhs))
             });
  mod.method("con_Electron", []() { JULIA_XDIAG_CALL_RETURN(Electron()) });
  mod.method("con_Electron",
             [](int64_t nsites) { JULIA_XDIAG_CALL_RETURN(Electron(nsites)) });
  mod.method("con_Electron", [](int64_t nsites, int64_t nup, int64_t ndn) {
    JULIA_XDIAG_CALL_RETURN(Electron(nsites, nup, ndn))
  });
  mod.method("con_Electron", [](int64_t nsites, Representation const &irrep) {
    JULIA_XDIAG_CALL_RETURN(Electron(nsites, irrep))
  });
  mod.method("con_Electron", [](int64_t nsites, int64_t nup, int64_t ndn,
                                Representation const &irrep) {
    JULIA_XDIAG_CALL_RETURN(Electron(nsites, nup, ndn, irrep))
  });
  mod.method("mth_nsites", [](const Electron &self) {
    JULIA_XDIAG_CALL_RETURN(self.nsites())
  });
  mod.method("mth_d", [](Electron &self) { JULIA_XDIAG_CALL_RETURN(self.d()) });
  mod.method("mth_dim",
             [](const Electron &self) { JULIA_XDIAG_CALL_RETURN(self.dim()) });
  mod.method("mth_size",
             [](const Electron &self) { JULIA_XDIAG_CALL_RETURN(self.size()) });
  mod.method("mth_isreal", [](const Electron &self) {
    JULIA_XDIAG_CALL_RETURN(self.isreal())
  });
  mod.method("mth_index", [](Electron const &self, ProductState const &pstate) {
    JULIA_XDIAG_CALL_RETURN(self.index(pstate))
  });
  mod.method("mth_operator==", [](Electron const &self, Electron const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
  });
  mod.method("mth_operator!=", [](Electron const &self, Electron const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator!=(rhs))
  });
  mod.method("con_ElectronIterator", [](Electron const *block, int64_t idx) {
    JULIA_XDIAG_CALL_RETURN(ElectronIterator(block, idx))
  });
  mod.method("mth_operator*", [](const ElectronIterator &self) {
    JULIA_XDIAG_CALL_RETURN(self.operator*())
  });
  mod.method("mth_operator==",
             [](ElectronIterator const &self, ElectronIterator const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
             });
  mod.method("mth_operator!=",
             [](ElectronIterator const &self, ElectronIterator const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator!=(rhs))
             });
  mod.method("con_Fermion", []() { JULIA_XDIAG_CALL_RETURN(Fermion()) });
  mod.method("con_Fermion",
             [](int64_t nsites) { JULIA_XDIAG_CALL_RETURN(Fermion(nsites)) });
  mod.method("con_Fermion", [](int64_t nsites, int64_t number) {
    JULIA_XDIAG_CALL_RETURN(Fermion(nsites, number))
  });
  mod.method("con_Fermion", [](int64_t nsites, Representation const &irrep) {
    JULIA_XDIAG_CALL_RETURN(Fermion(nsites, irrep))
  });
  mod.method("con_Fermion",
             [](int64_t nsites, int64_t number, Representation const &irrep) {
               JULIA_XDIAG_CALL_RETURN(Fermion(nsites, number, irrep))
             });
  mod.method("mth_nsites", [](const Fermion &self) {
    JULIA_XDIAG_CALL_RETURN(self.nsites())
  });
  mod.method("mth_d", [](Fermion &self) { JULIA_XDIAG_CALL_RETURN(self.d()) });
  mod.method("mth_dim",
             [](const Fermion &self) { JULIA_XDIAG_CALL_RETURN(self.dim()) });
  mod.method("mth_size",
             [](const Fermion &self) { JULIA_XDIAG_CALL_RETURN(self.size()) });
  mod.method("mth_isreal", [](const Fermion &self) {
    JULIA_XDIAG_CALL_RETURN(self.isreal())
  });
  mod.method("mth_index", [](Fermion const &self, ProductState const &pstate) {
    JULIA_XDIAG_CALL_RETURN(self.index(pstate))
  });
  mod.method("mth_operator==", [](Fermion const &self, Fermion const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
  });
  mod.method("mth_operator!=", [](Fermion const &self, Fermion const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator!=(rhs))
  });
  mod.method("con_FermionIterator", [](Fermion const *block, int64_t idx) {
    JULIA_XDIAG_CALL_RETURN(FermionIterator(block, idx))
  });
  mod.method("mth_operator*", [](const FermionIterator &self) {
    JULIA_XDIAG_CALL_RETURN(self.operator*())
  });
  mod.method("mth_operator==",
             [](FermionIterator const &self, FermionIterator const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
             });
  mod.method("mth_operator!=",
             [](FermionIterator const &self, FermionIterator const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator!=(rhs))
             });
  mod.method("con_Spinhalf", []() { JULIA_XDIAG_CALL_RETURN(Spinhalf()) });
  mod.method("con_Spinhalf",
             [](int64_t nsites) { JULIA_XDIAG_CALL_RETURN(Spinhalf(nsites)) });
  mod.method("con_Spinhalf", [](int64_t nsites, int64_t nup) {
    JULIA_XDIAG_CALL_RETURN(Spinhalf(nsites, nup))
  });
  mod.method("con_Spinhalf", [](int64_t nsites, Representation const &irrep,
                                std::string backend = "auto") {
    JULIA_XDIAG_CALL_RETURN(Spinhalf(nsites, irrep, "auto"))
  });
  mod.method("con_Spinhalf",
             [](int64_t nsites, int64_t nup, Representation const &irrep,
                std::string backend = "auto") {
               JULIA_XDIAG_CALL_RETURN(Spinhalf(nsites, nup, irrep, "auto"))
             });
  mod.method("mth_nsites", [](const Spinhalf &self) {
    JULIA_XDIAG_CALL_RETURN(self.nsites())
  });
  mod.method("mth_d", [](Spinhalf &self) { JULIA_XDIAG_CALL_RETURN(self.d()) });
  mod.method("mth_dim",
             [](const Spinhalf &self) { JULIA_XDIAG_CALL_RETURN(self.dim()) });
  mod.method("mth_size",
             [](const Spinhalf &self) { JULIA_XDIAG_CALL_RETURN(self.size()) });
  mod.method("mth_isreal", [](const Spinhalf &self) {
    JULIA_XDIAG_CALL_RETURN(self.isreal())
  });
  mod.method("mth_index", [](Spinhalf const &self, ProductState const &pstate) {
    JULIA_XDIAG_CALL_RETURN(self.index(pstate))
  });
  mod.method("mth_operator==", [](Spinhalf const &self, Spinhalf const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
  });
  mod.method("mth_operator!=", [](Spinhalf const &self, Spinhalf const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator!=(rhs))
  });
  mod.method("con_SpinhalfIterator", [](Spinhalf const *block, int64_t idx) {
    JULIA_XDIAG_CALL_RETURN(SpinhalfIterator(block, idx))
  });
  mod.method("mth_operator*", [](const SpinhalfIterator &self) {
    JULIA_XDIAG_CALL_RETURN(self.operator*())
  });
  mod.method("mth_operator==",
             [](SpinhalfIterator const &self, SpinhalfIterator const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
             });
  mod.method("mth_operator!=",
             [](SpinhalfIterator const &self, SpinhalfIterator const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator!=(rhs))
             });
  mod.method("con_tJ", []() { JULIA_XDIAG_CALL_RETURN(tJ()) });
  mod.method("con_tJ",
             [](int64_t nsites) { JULIA_XDIAG_CALL_RETURN(tJ(nsites)) });
  mod.method("con_tJ", [](int64_t nsites, int64_t nup, int64_t ndn) {
    JULIA_XDIAG_CALL_RETURN(tJ(nsites, nup, ndn))
  });
  mod.method("con_tJ", [](int64_t nsites, Representation const &irrep) {
    JULIA_XDIAG_CALL_RETURN(tJ(nsites, irrep))
  });
  mod.method("con_tJ", [](int64_t nsites, int64_t nup, int64_t ndn,
                          Representation const &irrep) {
    JULIA_XDIAG_CALL_RETURN(tJ(nsites, nup, ndn, irrep))
  });
  mod.method("mth_nsites",
             [](const tJ &self) { JULIA_XDIAG_CALL_RETURN(self.nsites()) });
  mod.method("mth_d", [](tJ &self) { JULIA_XDIAG_CALL_RETURN(self.d()) });
  mod.method("mth_dim",
             [](const tJ &self) { JULIA_XDIAG_CALL_RETURN(self.dim()) });
  mod.method("mth_size",
             [](const tJ &self) { JULIA_XDIAG_CALL_RETURN(self.size()) });
  mod.method("mth_isreal",
             [](const tJ &self) { JULIA_XDIAG_CALL_RETURN(self.isreal()) });
  mod.method("mth_index", [](tJ const &self, ProductState const &pstate) {
    JULIA_XDIAG_CALL_RETURN(self.index(pstate))
  });
  mod.method("mth_operator==", [](tJ const &self, tJ const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
  });
  mod.method("mth_operator!=", [](tJ const &self, tJ const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator!=(rhs))
  });
  mod.method("con_tJIterator", [](tJ const *block, int64_t idx) {
    JULIA_XDIAG_CALL_RETURN(tJIterator(block, idx))
  });
  mod.method("mth_operator*", [](const tJIterator &self) {
    JULIA_XDIAG_CALL_RETURN(self.operator*())
  });
  mod.method("mth_operator==",
             [](tJIterator const &self, tJIterator const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
             });
  mod.method("mth_operator!=",
             [](tJIterator const &self, tJIterator const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator!=(rhs))
             });
}
} // namespace xdiag::julia
