// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_submodule.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {
void define_io(jlcxx::Module &mod) {
  using namespace xdiag;
  mod.method("con_FileToml", []() { JULIA_XDIAG_CALL_RETURN(FileToml()) });
  mod.method("con_FileToml", [](const char *filename) {
    JULIA_XDIAG_CALL_RETURN(FileToml(filename))
  });
  mod.method("con_FileToml", [](std::string filename) {
    JULIA_XDIAG_CALL_RETURN(FileToml(filename))
  });
  mod.method("mth_defined", [](FileToml const &self, std::string key) {
    JULIA_XDIAG_CALL_RETURN(self.defined(key))
  });
  mod.method("mth_write",
             [](FileToml const &self, std::string filename, std::string mode) {
               JULIA_XDIAG_CALL_VOID(self.write(filename, mode));
             });
  mod.method("mth_keys",
             [](const FileToml &self) { JULIA_XDIAG_CALL_RETURN(self.keys()) });
  mod.method("fun_defined", [](FileToml const &fl, std::string key) {
    JULIA_XDIAG_CALL_RETURN(defined(fl, key))
  });
  mod.method("fun_read_permutation", [](FileToml file, std::string tag) {
    JULIA_XDIAG_CALL_RETURN(read_permutation(file, tag))
  });
  mod.method("fun_read_permutation_group", [](FileToml file, std::string tag) {
    JULIA_XDIAG_CALL_RETURN(read_permutation_group(file, tag))
  });
  mod.method("fun_read_representation", [](FileToml file, std::string irrep_tag,
                                           std::string group_tag) {
    JULIA_XDIAG_CALL_RETURN(read_representation(file, irrep_tag, group_tag))
  });
  mod.method("fun_read_op", [](FileToml file, std::string tag) {
    JULIA_XDIAG_CALL_RETURN(read_op(file, tag))
  });
  mod.method("fun_read_opsum", [](FileToml file, std::string tag) {
    JULIA_XDIAG_CALL_RETURN(read_opsum(file, tag))
  });

  // operator overloads
  mod.method("op_isequal", [](FileToml const &self, FileToml const &other) {
    JULIA_XDIAG_CALL_RETURN(self.operator==(other))
  });
}
} // namespace xdiag::julia
