set(XDIAG_JULIA_SOURCES
    src/xdiagjl.cpp
    src/types.cpp
    src/modules.cpp
    src/algebra.cpp
    src/basis.cpp
    src/bits.cpp
    src/blocks.cpp
    src/combinatorics.cpp
    src/io.cpp
    src/kernels.cpp
    src/linalg.cpp
    src/math.cpp
    src/mpi.cpp
    src/operators.cpp
    src/random.cpp
    src/states.cpp
    src/symmetries.cpp
    src/utils.cpp
)
