// GENERATED by model_sketch -- DO NOT EDIT.
#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {
void define_kernels(jlcxx::Module &mod) {
  using namespace xdiag;
  mod.method("fun_isreal", [](CSRMatrix<int64_t, double> const &A) {
    JULIA_XDIAG_CALL_RETURN(isreal(A))
  });
  mod.method("fun_isreal", [](CSRMatrix<int64_t, complex> const &A) {
    JULIA_XDIAG_CALL_RETURN(isreal(A))
  });
  mod.method("fun_isreal", [](CSRMatrix<int32_t, double> const &A) {
    JULIA_XDIAG_CALL_RETURN(isreal(A))
  });
  mod.method("fun_isreal", [](CSRMatrix<int32_t, complex> const &A) {
    JULIA_XDIAG_CALL_RETURN(isreal(A))
  });
  mod.method("fun_ishermitian", [](CSRMatrix<int64_t, double> const &A) {
    JULIA_XDIAG_CALL_RETURN(ishermitian(A))
  });
  mod.method("fun_ishermitian", [](CSRMatrix<int64_t, complex> const &A) {
    JULIA_XDIAG_CALL_RETURN(ishermitian(A))
  });
  mod.method("fun_ishermitian", [](CSRMatrix<int32_t, double> const &A) {
    JULIA_XDIAG_CALL_RETURN(ishermitian(A))
  });
  mod.method("fun_ishermitian", [](CSRMatrix<int32_t, complex> const &A) {
    JULIA_XDIAG_CALL_RETURN(ishermitian(A))
  });
}
} // namespace xdiag::julia
