// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_submodule.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {
void define_kernels(jlcxx::Module &mod) {
  using namespace xdiag;
  mod.method("fun_coo_matrix",
             [](OpSum const &ops, Block const &block, int64_t i0 = 0) {
               JULIA_XDIAG_CALL_RETURN(coo_matrix(ops, block, 0))
             });
  mod.method("fun_coo_matrix", [](OpSum const &ops, Block const &block_in,
                                  Block const &block_out, int64_t i0 = 0) {
    JULIA_XDIAG_CALL_RETURN(coo_matrix(ops, block_in, block_out, 0))
  });
  mod.method("fun_coo_matrixC",
             [](OpSum const &ops, Block const &block, int64_t i0 = 0) {
               JULIA_XDIAG_CALL_RETURN(coo_matrixC(ops, block, 0))
             });
  mod.method("fun_coo_matrixC", [](OpSum const &ops, Block const &block_in,
                                   Block const &block_out, int64_t i0 = 0) {
    JULIA_XDIAG_CALL_RETURN(coo_matrixC(ops, block_in, block_out, 0))
  });
  mod.method("fun_coo_matrix_32",
             [](OpSum const &ops, Block const &block, int32_t i0 = 0) {
               JULIA_XDIAG_CALL_RETURN(coo_matrix_32(ops, block, 0))
             });
  mod.method("fun_coo_matrix_32", [](OpSum const &ops, Block const &block_in,
                                     Block const &block_out, int32_t i0 = 0) {
    JULIA_XDIAG_CALL_RETURN(coo_matrix_32(ops, block_in, block_out, 0))
  });
  mod.method("fun_coo_matrixC_32",
             [](OpSum const &ops, Block const &block, int32_t i0 = 0) {
               JULIA_XDIAG_CALL_RETURN(coo_matrixC_32(ops, block, 0))
             });
  mod.method("fun_coo_matrixC_32", [](OpSum const &ops, Block const &block_in,
                                      Block const &block_out, int32_t i0 = 0) {
    JULIA_XDIAG_CALL_RETURN(coo_matrixC_32(ops, block_in, block_out, 0))
  });
  mod.method("fun_csc_matrix",
             [](OpSum const &ops, Block const &block, int64_t i0 = 0) {
               JULIA_XDIAG_CALL_RETURN(csc_matrix(ops, block, 0))
             });
  mod.method("fun_csc_matrix", [](OpSum const &ops, Block const &block_in,
                                  Block const &block_out, int64_t i0 = 0) {
    JULIA_XDIAG_CALL_RETURN(csc_matrix(ops, block_in, block_out, 0))
  });
  mod.method("fun_csc_matrixC",
             [](OpSum const &ops, Block const &block, int64_t i0 = 0) {
               JULIA_XDIAG_CALL_RETURN(csc_matrixC(ops, block, 0))
             });
  mod.method("fun_csc_matrixC", [](OpSum const &ops, Block const &block_in,
                                   Block const &block_out, int64_t i0 = 0) {
    JULIA_XDIAG_CALL_RETURN(csc_matrixC(ops, block_in, block_out, 0))
  });
  mod.method("fun_csc_matrix_32",
             [](OpSum const &ops, Block const &block, int32_t i0 = 0) {
               JULIA_XDIAG_CALL_RETURN(csc_matrix_32(ops, block, 0))
             });
  mod.method("fun_csc_matrix_32", [](OpSum const &ops, Block const &block_in,
                                     Block const &block_out, int32_t i0 = 0) {
    JULIA_XDIAG_CALL_RETURN(csc_matrix_32(ops, block_in, block_out, 0))
  });
  mod.method("fun_csc_matrixC_32",
             [](OpSum const &ops, Block const &block, int32_t i0 = 0) {
               JULIA_XDIAG_CALL_RETURN(csc_matrixC_32(ops, block, 0))
             });
  mod.method("fun_csc_matrixC_32", [](OpSum const &ops, Block const &block_in,
                                      Block const &block_out, int32_t i0 = 0) {
    JULIA_XDIAG_CALL_RETURN(csc_matrixC_32(ops, block_in, block_out, 0))
  });
  mod.method("fun_csr_matrix",
             [](OpSum const &ops, Block const &block, int64_t i0 = 0) {
               JULIA_XDIAG_CALL_RETURN(csr_matrix(ops, block, 0))
             });
  mod.method("fun_csr_matrix", [](OpSum const &ops, Block const &block_in,
                                  Block const &block_out, int64_t i0 = 0) {
    JULIA_XDIAG_CALL_RETURN(csr_matrix(ops, block_in, block_out, 0))
  });
  mod.method("fun_csr_matrixC",
             [](OpSum const &ops, Block const &block, int64_t i0 = 0) {
               JULIA_XDIAG_CALL_RETURN(csr_matrixC(ops, block, 0))
             });
  mod.method("fun_csr_matrixC", [](OpSum const &ops, Block const &block_in,
                                   Block const &block_out, int64_t i0 = 0) {
    JULIA_XDIAG_CALL_RETURN(csr_matrixC(ops, block_in, block_out, 0))
  });
  mod.method("fun_csr_matrix_32",
             [](OpSum const &ops, Block const &block, int32_t i0 = 0) {
               JULIA_XDIAG_CALL_RETURN(csr_matrix_32(ops, block, 0))
             });
  mod.method("fun_csr_matrix_32", [](OpSum const &ops, Block const &block_in,
                                     Block const &block_out, int32_t i0 = 0) {
    JULIA_XDIAG_CALL_RETURN(csr_matrix_32(ops, block_in, block_out, 0))
  });
  mod.method("fun_csr_matrixC_32",
             [](OpSum const &ops, Block const &block, int32_t i0 = 0) {
               JULIA_XDIAG_CALL_RETURN(csr_matrixC_32(ops, block, 0))
             });
  mod.method("fun_csr_matrixC_32", [](OpSum const &ops, Block const &block_in,
                                      Block const &block_out, int32_t i0 = 0) {
    JULIA_XDIAG_CALL_RETURN(csr_matrixC_32(ops, block_in, block_out, 0))
  });
}
} // namespace xdiag::julia
