// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_submodule.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {
void define_linalg(jlcxx::Module &mod) {
  using namespace xdiag;
  mod.method("fun_eigs_lanczos",
             [](OpSum const &ops, Block const &block, int64_t neigvals = 1,
                double precision = 1e-12, int64_t max_iterations = 1000,
                double deflation_tol = 1e-7, int64_t random_seed = 42) {
               JULIA_XDIAG_CALL_RETURN(
                   eigs_lanczos(ops, block, 1, 1e-12, 1000, 1e-7, 42))
             });
  mod.method("fun_eigs_lanczos", [](OpSum const &ops, State const &state0,
                                    int64_t neigvals = 1,
                                    double precision = 1e-12,
                                    int64_t max_iterations = 1000,
                                    double deflation_tol = 1e-7) {
    JULIA_XDIAG_CALL_RETURN(eigs_lanczos(ops, state0, 1, 1e-12, 1000, 1e-7))
  });
  mod.method("fun_eigvals_lanczos",
             [](OpSum const &ops, Block const &block, int64_t neigvals = 1,
                double precision = 1e-12, int64_t max_iterations = 1000,
                double deflation_tol = 1e-7, int64_t random_seed = 42) {
               JULIA_XDIAG_CALL_RETURN(
                   eigvals_lanczos(ops, block, 1, 1e-12, 1000, 1e-7, 42))
             });
  mod.method("fun_eigvals_lanczos", [](OpSum const &ops, State psi0,
                                       int64_t neigvals = 1,
                                       double precision = 1e-12,
                                       int64_t max_iterations = 1000,
                                       double deflation_tol = 1e-7) {
    JULIA_XDIAG_CALL_RETURN(eigvals_lanczos(ops, psi0, 1, 1e-12, 1000, 1e-7))
  });
  mod.method("fun_eigvals_lanczos_inplace",
             [](OpSum const &ops, State &psi0, int64_t neigvals = 1,
                double precision = 1e-12, int64_t max_iterations = 1000,
                double deflation_tol = 1e-7) {
               JULIA_XDIAG_CALL_RETURN(
                   eigvals_lanczos_inplace(ops, psi0, 1, 1e-12, 1000, 1e-7))
             });
  mod.method("fun_eigs_lobpcg", [](OpSum const &ops, Block const &block,
                                   int64_t neigs = 1, int64_t guard = 2,
                                   double tol = 1e-10,
                                   int64_t max_iterations = 1000,
                                   int64_t random_seed = 42) {
    JULIA_XDIAG_CALL_RETURN(eigs_lobpcg(ops, block, 1, 2, 1e-10, 1000, 42))
  });
  mod.method("fun_eigval0",
             [](OpSum const &ops, Block const &block, double precision = 1e-12,
                int64_t max_iterations = 1000, int64_t random_seed = 42) {
               JULIA_XDIAG_CALL_RETURN(eigval0(ops, block, 1e-12, 1000, 42))
             });
  mod.method("fun_eig0",
             [](OpSum const &ops, Block const &block, double precision = 1e-12,
                int64_t max_iterations = 1000, int64_t random_seed = 42) {
               JULIA_XDIAG_CALL_RETURN(eig0(ops, block, 1e-12, 1000, 42))
             });
  mod.method("fun_eigvals", [](OpSum const &ops, Block const &block,
                               int64_t neigs, double precision = 1e-12,
                               int64_t max_iterations = 1000,
                               int64_t random_seed = 42) {
    JULIA_XDIAG_CALL_RETURN(eigvals(ops, block, neigs, 1e-12, 1000, 42))
  });
  mod.method("fun_eigs",
             [](OpSum const &ops, Block const &block, int64_t neigs,
                double precision = 1e-12, int64_t max_iterations = 1000,
                int64_t random_seed = 42) {
               JULIA_XDIAG_CALL_RETURN(eigs(ops, block, neigs, 1e-12, 1000, 42))
             });
  mod.method("fun_evolve_lanczos",
             [](OpSum const &H, State psi, double tau, double precision = 1e-12,
                double shift = 0., bool normalize = false,
                int64_t max_iterations = 1000, double deflation_tol = 1e-7) {
               JULIA_XDIAG_CALL_RETURN(
                   evolve_lanczos(H, psi, tau, 1e-12, 0., false, 1000, 1e-7))
             });
  mod.method("fun_evolve_lanczos",
             [](OpSum const &H, State psi, complex tau,
                double precision = 1e-12, double shift = 0.,
                bool normalize = false, int64_t max_iterations = 1000,
                double deflation_tol = 1e-7) {
               JULIA_XDIAG_CALL_RETURN(
                   evolve_lanczos(H, psi, tau, 1e-12, 0., false, 1000, 1e-7))
             });
  mod.method(
      "fun_evolve_lanczos_inplace",
      [](OpSum const &H, State &psi, double tau, double precision = 1e-12,
         double shift = 0., bool normalize = false,
         int64_t max_iterations = 1000, double deflation_tol = 1e-7) {
        JULIA_XDIAG_CALL_RETURN(
            evolve_lanczos_inplace(H, psi, tau, 1e-12, 0., false, 1000, 1e-7))
      });
  mod.method(
      "fun_evolve_lanczos_inplace",
      [](OpSum const &H, State &psi, complex tau, double precision = 1e-12,
         double shift = 0., bool normalize = false,
         int64_t max_iterations = 1000, double deflation_tol = 1e-7) {
        JULIA_XDIAG_CALL_RETURN(
            evolve_lanczos_inplace(H, psi, tau, 1e-12, 0., false, 1000, 1e-7))
      });
  mod.method("fun_imaginary_time_evolve", [](OpSum const &H, State psi,
                                             double time,
                                             double precision = 1e-12,
                                             double shift = 0.) {
    JULIA_XDIAG_CALL_RETURN(imaginary_time_evolve(H, psi, time, 1e-12, 0.))
  });
  mod.method("fun_imaginary_time_evolve_inplace",
             [](OpSum const &H, State &psi, double time,
                double precision = 1e-12, double shift = 0.) {
               JULIA_XDIAG_CALL_VOID(
                   imaginary_time_evolve_inplace(H, psi, time, 1e-12, 0.));
             });
  mod.method("fun_time_evolve", [](OpSum const &H, State psi, double time,
                                   double precision = 1e-12,
                                   std::string algorithm = "lanczos") {
    JULIA_XDIAG_CALL_RETURN(time_evolve(H, psi, time, 1e-12, "lanczos"))
  });
  mod.method("fun_time_evolve_inplace", [](OpSum const &H, State &psi,
                                           double time,
                                           double precision = 1e-12,
                                           std::string algorithm = "lanczos") {
    JULIA_XDIAG_CALL_VOID(time_evolve_inplace(H, psi, time, 1e-12, "lanczos"));
  });
  mod.method("fun_time_evolve_expokit",
             [](OpSum const &H, State psi0, double time,
                double precision = 1e-12, int64_t m = 30, double anorm = 0.,
                int64_t nnorm = 2) {
               JULIA_XDIAG_CALL_RETURN(
                   time_evolve_expokit(H, psi0, time, 1e-12, 30, 0., 2))
             });
  mod.method("fun_time_evolve_expokit_inplace",
             [](OpSum const &H, State &psi, double time,
                double precision = 1e-12, int64_t m = 30, double anorm = 0.,
                int64_t nnorm = 2) {
               JULIA_XDIAG_CALL_RETURN(
                   time_evolve_expokit_inplace(H, psi, time, 1e-12, 30, 0., 2))
             });
}
} // namespace xdiag::julia
