// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_submodule.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {
void define_linalg(jlcxx::Module &mod) {
  using namespace xdiag;
  mod.method("mth_alphas",
             [](EigsLanczosResult const &self) { return self.alphas; });
  mod.method("mth_betas",
             [](EigsLanczosResult const &self) { return self.betas; });
  mod.method("mth_eigenvalues",
             [](EigsLanczosResult const &self) { return self.eigenvalues; });
  mod.method("mth_eigenvectors",
             [](EigsLanczosResult const &self) { return self.eigenvectors; });
  mod.method("mth_niterations",
             [](EigsLanczosResult const &self) { return self.niterations; });
  mod.method("mth_criterion",
             [](EigsLanczosResult const &self) { return self.criterion; });
  mod.method("fun_eigs_lanczos",
             [](OpSum const &ops, Fermion const &block, int64_t neigvals,
                double precision, int64_t max_iterations, double deflation_tol,
                int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(eigs_lanczos(ops, block, neigvals,
                                                    precision, max_iterations,
                                                    deflation_tol, random_seed))
             });
  mod.method("fun_eigs_lanczos",
             [](OpSum const &ops, Boson const &block, int64_t neigvals,
                double precision, int64_t max_iterations, double deflation_tol,
                int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(eigs_lanczos(ops, block, neigvals,
                                                    precision, max_iterations,
                                                    deflation_tol, random_seed))
             });
  mod.method("fun_eigs_lanczos",
             [](OpSum const &ops, Spinhalf const &block, int64_t neigvals,
                double precision, int64_t max_iterations, double deflation_tol,
                int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(eigs_lanczos(ops, block, neigvals,
                                                    precision, max_iterations,
                                                    deflation_tol, random_seed))
             });
  mod.method("fun_eigs_lanczos",
             [](OpSum const &ops, Electron const &block, int64_t neigvals,
                double precision, int64_t max_iterations, double deflation_tol,
                int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(eigs_lanczos(ops, block, neigvals,
                                                    precision, max_iterations,
                                                    deflation_tol, random_seed))
             });
  mod.method("fun_eigs_lanczos",
             [](OpSum const &ops, tJ const &block, int64_t neigvals,
                double precision, int64_t max_iterations, double deflation_tol,
                int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(eigs_lanczos(ops, block, neigvals,
                                                    precision, max_iterations,
                                                    deflation_tol, random_seed))
             });
  mod.method("fun_eigs_lanczos", [](OpSum const &ops, State const &state0,
                                    int64_t neigvals, double precision,
                                    int64_t max_iterations,
                                    double deflation_tol) {
    JULIA_XDIAG_CALL_RETURN(eigs_lanczos(ops, state0, neigvals, precision,
                                         max_iterations, deflation_tol))
  });
  mod.method("mth_alphas",
             [](EigvalsLanczosResult const &self) { return self.alphas; });
  mod.method("mth_betas",
             [](EigvalsLanczosResult const &self) { return self.betas; });
  mod.method("mth_eigenvalues",
             [](EigvalsLanczosResult const &self) { return self.eigenvalues; });
  mod.method("mth_niterations",
             [](EigvalsLanczosResult const &self) { return self.niterations; });
  mod.method("mth_criterion",
             [](EigvalsLanczosResult const &self) { return self.criterion; });
  mod.method("fun_eigvals_lanczos",
             [](OpSum const &ops, Fermion const &block, int64_t neigvals,
                double precision, int64_t max_iterations, double deflation_tol,
                int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(
                   eigvals_lanczos(ops, block, neigvals, precision,
                                   max_iterations, deflation_tol, random_seed))
             });
  mod.method("fun_eigvals_lanczos",
             [](OpSum const &ops, Boson const &block, int64_t neigvals,
                double precision, int64_t max_iterations, double deflation_tol,
                int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(
                   eigvals_lanczos(ops, block, neigvals, precision,
                                   max_iterations, deflation_tol, random_seed))
             });
  mod.method("fun_eigvals_lanczos",
             [](OpSum const &ops, Spinhalf const &block, int64_t neigvals,
                double precision, int64_t max_iterations, double deflation_tol,
                int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(
                   eigvals_lanczos(ops, block, neigvals, precision,
                                   max_iterations, deflation_tol, random_seed))
             });
  mod.method("fun_eigvals_lanczos",
             [](OpSum const &ops, Electron const &block, int64_t neigvals,
                double precision, int64_t max_iterations, double deflation_tol,
                int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(
                   eigvals_lanczos(ops, block, neigvals, precision,
                                   max_iterations, deflation_tol, random_seed))
             });
  mod.method("fun_eigvals_lanczos",
             [](OpSum const &ops, tJ const &block, int64_t neigvals,
                double precision, int64_t max_iterations, double deflation_tol,
                int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(
                   eigvals_lanczos(ops, block, neigvals, precision,
                                   max_iterations, deflation_tol, random_seed))
             });
  mod.method("fun_eigvals_lanczos", [](OpSum const &ops, State psi0,
                                       int64_t neigvals, double precision,
                                       int64_t max_iterations,
                                       double deflation_tol) {
    JULIA_XDIAG_CALL_RETURN(eigvals_lanczos(ops, psi0, neigvals, precision,
                                            max_iterations, deflation_tol))
  });
  mod.method(
      "fun_eigvals_lanczos_inplace",
      [](OpSum const &ops, State &psi0, int64_t neigvals, double precision,
         int64_t max_iterations, double deflation_tol) {
        JULIA_XDIAG_CALL_RETURN(eigvals_lanczos_inplace(
            ops, psi0, neigvals, precision, max_iterations, deflation_tol))
      });
  mod.method("mth_eigenvalues",
             [](EigsLobpcgResult const &self) { return self.eigenvalues; });
  mod.method("mth_residual_norms",
             [](EigsLobpcgResult const &self) { return self.residual_norms; });
  mod.method("mth_eigenvectors",
             [](EigsLobpcgResult const &self) { return self.eigenvectors; });
  mod.method("mth_niterations",
             [](EigsLobpcgResult const &self) { return self.niterations; });
  mod.method("mth_criterion",
             [](EigsLobpcgResult const &self) { return self.criterion; });
  mod.method("mth_eigenvalue_history", [](EigsLobpcgResult const &self) {
    return self.eigenvalue_history;
  });
  mod.method("mth_residual_norms_history", [](EigsLobpcgResult const &self) {
    return self.residual_norms_history;
  });
  mod.method("fun_eigs_lobpcg", [](OpSum const &ops, Fermion const &block,
                                   int64_t neigs, int64_t guard, double tol,
                                   int64_t max_iterations,
                                   int64_t random_seed) {
    JULIA_XDIAG_CALL_RETURN(
        eigs_lobpcg(ops, block, neigs, guard, tol, max_iterations, random_seed))
  });
  mod.method("fun_eigs_lobpcg", [](OpSum const &ops, Boson const &block,
                                   int64_t neigs, int64_t guard, double tol,
                                   int64_t max_iterations,
                                   int64_t random_seed) {
    JULIA_XDIAG_CALL_RETURN(
        eigs_lobpcg(ops, block, neigs, guard, tol, max_iterations, random_seed))
  });
  mod.method("fun_eigs_lobpcg", [](OpSum const &ops, Spinhalf const &block,
                                   int64_t neigs, int64_t guard, double tol,
                                   int64_t max_iterations,
                                   int64_t random_seed) {
    JULIA_XDIAG_CALL_RETURN(
        eigs_lobpcg(ops, block, neigs, guard, tol, max_iterations, random_seed))
  });
  mod.method("fun_eigs_lobpcg", [](OpSum const &ops, Electron const &block,
                                   int64_t neigs, int64_t guard, double tol,
                                   int64_t max_iterations,
                                   int64_t random_seed) {
    JULIA_XDIAG_CALL_RETURN(
        eigs_lobpcg(ops, block, neigs, guard, tol, max_iterations, random_seed))
  });
  mod.method("fun_eigs_lobpcg",
             [](OpSum const &ops, tJ const &block, int64_t neigs, int64_t guard,
                double tol, int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(eigs_lobpcg(
                   ops, block, neigs, guard, tol, max_iterations, random_seed))
             });
  mod.method("fun_eigval0",
             [](OpSum const &ops, Fermion const &block, double precision,
                int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(
                   eigval0(ops, block, precision, max_iterations, random_seed))
             });
  mod.method("fun_eigval0",
             [](OpSum const &ops, Boson const &block, double precision,
                int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(
                   eigval0(ops, block, precision, max_iterations, random_seed))
             });
  mod.method("fun_eigval0",
             [](OpSum const &ops, Spinhalf const &block, double precision,
                int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(
                   eigval0(ops, block, precision, max_iterations, random_seed))
             });
  mod.method("fun_eigval0",
             [](OpSum const &ops, Electron const &block, double precision,
                int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(
                   eigval0(ops, block, precision, max_iterations, random_seed))
             });
  mod.method("fun_eigval0",
             [](OpSum const &ops, tJ const &block, double precision,
                int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(
                   eigval0(ops, block, precision, max_iterations, random_seed))
             });
  mod.method("fun_eig0",
             [](OpSum const &ops, Fermion const &block, double precision,
                int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(
                   eig0(ops, block, precision, max_iterations, random_seed))
             });
  mod.method("fun_eig0",
             [](OpSum const &ops, Boson const &block, double precision,
                int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(
                   eig0(ops, block, precision, max_iterations, random_seed))
             });
  mod.method("fun_eig0",
             [](OpSum const &ops, Spinhalf const &block, double precision,
                int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(
                   eig0(ops, block, precision, max_iterations, random_seed))
             });
  mod.method("fun_eig0",
             [](OpSum const &ops, Electron const &block, double precision,
                int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(
                   eig0(ops, block, precision, max_iterations, random_seed))
             });
  mod.method("fun_eig0", [](OpSum const &ops, tJ const &block, double precision,
                            int64_t max_iterations, int64_t random_seed) {
    JULIA_XDIAG_CALL_RETURN(
        eig0(ops, block, precision, max_iterations, random_seed))
  });
  mod.method("fun_eigvals",
             [](OpSum const &ops, Fermion const &block, int64_t neigs,
                double precision, int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(eigvals(ops, block, neigs, precision,
                                               max_iterations, random_seed))
             });
  mod.method("fun_eigvals",
             [](OpSum const &ops, Boson const &block, int64_t neigs,
                double precision, int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(eigvals(ops, block, neigs, precision,
                                               max_iterations, random_seed))
             });
  mod.method("fun_eigvals",
             [](OpSum const &ops, Spinhalf const &block, int64_t neigs,
                double precision, int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(eigvals(ops, block, neigs, precision,
                                               max_iterations, random_seed))
             });
  mod.method("fun_eigvals",
             [](OpSum const &ops, Electron const &block, int64_t neigs,
                double precision, int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(eigvals(ops, block, neigs, precision,
                                               max_iterations, random_seed))
             });
  mod.method("fun_eigvals",
             [](OpSum const &ops, tJ const &block, int64_t neigs,
                double precision, int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(eigvals(ops, block, neigs, precision,
                                               max_iterations, random_seed))
             });
  mod.method("fun_eigs",
             [](OpSum const &ops, Fermion const &block, int64_t neigs,
                double precision, int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(eigs(ops, block, neigs, precision,
                                            max_iterations, random_seed))
             });
  mod.method("fun_eigs",
             [](OpSum const &ops, Boson const &block, int64_t neigs,
                double precision, int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(eigs(ops, block, neigs, precision,
                                            max_iterations, random_seed))
             });
  mod.method("fun_eigs",
             [](OpSum const &ops, Spinhalf const &block, int64_t neigs,
                double precision, int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(eigs(ops, block, neigs, precision,
                                            max_iterations, random_seed))
             });
  mod.method("fun_eigs",
             [](OpSum const &ops, Electron const &block, int64_t neigs,
                double precision, int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(eigs(ops, block, neigs, precision,
                                            max_iterations, random_seed))
             });
  mod.method("fun_eigs",
             [](OpSum const &ops, tJ const &block, int64_t neigs,
                double precision, int64_t max_iterations, int64_t random_seed) {
               JULIA_XDIAG_CALL_RETURN(eigs(ops, block, neigs, precision,
                                            max_iterations, random_seed))
             });
  mod.method("mth_alphas",
             [](EvolveLanczosResult const &self) { return self.alphas; });
  mod.method("mth_betas",
             [](EvolveLanczosResult const &self) { return self.betas; });
  mod.method("mth_eigenvalues",
             [](EvolveLanczosResult const &self) { return self.eigenvalues; });
  mod.method("mth_niterations",
             [](EvolveLanczosResult const &self) { return self.niterations; });
  mod.method("mth_criterion",
             [](EvolveLanczosResult const &self) { return self.criterion; });
  mod.method("mth_state",
             [](EvolveLanczosResult const &self) { return self.state; });
  mod.method("fun_evolve_lanczos", [](OpSum const &H, State psi, double tau,
                                      double precision, double shift,
                                      bool normalize, int64_t max_iterations,
                                      double deflation_tol) {
    JULIA_XDIAG_CALL_RETURN(evolve_lanczos(H, psi, tau, precision, shift,
                                           normalize, max_iterations,
                                           deflation_tol))
  });
  mod.method("fun_evolve_lanczos", [](OpSum const &H, State psi, complex tau,
                                      double precision, double shift,
                                      bool normalize, int64_t max_iterations,
                                      double deflation_tol) {
    JULIA_XDIAG_CALL_RETURN(evolve_lanczos(H, psi, tau, precision, shift,
                                           normalize, max_iterations,
                                           deflation_tol))
  });
  mod.method("mth_alphas", [](EvolveLanczosInplaceResult const &self) {
    return self.alphas;
  });
  mod.method("mth_betas",
             [](EvolveLanczosInplaceResult const &self) { return self.betas; });
  mod.method("mth_eigenvalues", [](EvolveLanczosInplaceResult const &self) {
    return self.eigenvalues;
  });
  mod.method("mth_niterations", [](EvolveLanczosInplaceResult const &self) {
    return self.niterations;
  });
  mod.method("mth_criterion", [](EvolveLanczosInplaceResult const &self) {
    return self.criterion;
  });
  mod.method(
      "fun_evolve_lanczos_inplace",
      [](OpSum const &H, State &psi, double tau, double precision, double shift,
         bool normalize, int64_t max_iterations, double deflation_tol) {
        JULIA_XDIAG_CALL_RETURN(
            evolve_lanczos_inplace(H, psi, tau, precision, shift, normalize,
                                   max_iterations, deflation_tol))
      });
  mod.method("fun_evolve_lanczos_inplace",
             [](OpSum const &H, State &psi, complex tau, double precision,
                double shift, bool normalize, int64_t max_iterations,
                double deflation_tol) {
               JULIA_XDIAG_CALL_RETURN(evolve_lanczos_inplace(
                   H, psi, tau, precision, shift, normalize, max_iterations,
                   deflation_tol))
             });
  mod.method("fun_imaginary_time_evolve",
             [](OpSum const &H, State psi, double time, double precision,
                double shift) {
               JULIA_XDIAG_CALL_RETURN(
                   imaginary_time_evolve(H, psi, time, precision, shift))
             });
  mod.method("fun_imaginary_time_evolve_inplace",
             [](OpSum const &H, State &psi, double time, double precision,
                double shift) {
               JULIA_XDIAG_CALL_VOID(imaginary_time_evolve_inplace(
                   H, psi, time, precision, shift));
             });
  mod.method("fun_time_evolve", [](OpSum const &H, State psi, double time,
                                   double precision, std::string algorithm) {
    JULIA_XDIAG_CALL_RETURN(time_evolve(H, psi, time, precision, algorithm))
  });
  mod.method("fun_time_evolve_inplace",
             [](OpSum const &H, State &psi, double time, double precision,
                std::string algorithm) {
               JULIA_XDIAG_CALL_VOID(
                   time_evolve_inplace(H, psi, time, precision, algorithm));
             });
  mod.method("mth_error",
             [](TimeEvolveExpokitResult const &self) { return self.error; });
  mod.method("mth_hump",
             [](TimeEvolveExpokitResult const &self) { return self.hump; });
  mod.method("mth_state",
             [](TimeEvolveExpokitResult const &self) { return self.state; });
  mod.method("fun_time_evolve_expokit",
             [](OpSum const &H, State psi0, double time, double precision,
                int64_t m, double anorm, int64_t nnorm) {
               JULIA_XDIAG_CALL_RETURN(time_evolve_expokit(
                   H, psi0, time, precision, m, anorm, nnorm))
             });
  mod.method("mth_error", [](TimeEvolveExpokitInplaceResult const &self) {
    return self.error;
  });
  mod.method("mth_hump", [](TimeEvolveExpokitInplaceResult const &self) {
    return self.hump;
  });
  mod.method("fun_time_evolve_expokit_inplace",
             [](OpSum const &H, State &psi, double time, double precision,
                int64_t m, double anorm, int64_t nnorm) {
               JULIA_XDIAG_CALL_RETURN(time_evolve_expokit_inplace(
                   H, psi, time, precision, m, anorm, nnorm))
             });

  // operator overloads
}
} // namespace xdiag::julia
