// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen/create_wrapper.sh -- DO NOT EDIT.

#include "modules.hpp"

namespace xdiag::julia {

void define_modules(jlcxx::Module &mod) {
  define_algebra(mod);
  define_basis(mod);
  define_bits(mod);
  define_blocks(mod);
  define_combinatorics(mod);
  define_io(mod);
  define_kernels(mod);
  define_linalg(mod);
  define_math(mod);
  define_mpi(mod);
  define_operators(mod);
  define_random(mod);
  define_states(mod);
  define_symmetries(mod);
  define_utils(mod);
}
} // namespace xdiag::julia
