// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen/create_wrapper.sh -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>

namespace xdiag::julia {

void define_modules(jlcxx::Module &mod);

void define_algebra(jlcxx::Module &mod);
void define_basis(jlcxx::Module &mod);
void define_bits(jlcxx::Module &mod);
void define_blocks(jlcxx::Module &mod);
void define_combinatorics(jlcxx::Module &mod);
void define_io(jlcxx::Module &mod);
void define_kernels(jlcxx::Module &mod);
void define_linalg(jlcxx::Module &mod);
void define_math(jlcxx::Module &mod);
void define_mpi(jlcxx::Module &mod);
void define_operators(jlcxx::Module &mod);
void define_random(jlcxx::Module &mod);
void define_states(jlcxx::Module &mod);
void define_symmetries(jlcxx::Module &mod);
void define_utils(jlcxx::Module &mod);
} // namespace xdiag::julia
