// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_submodule.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {
void define_operators(jlcxx::Module &mod) {
  using namespace xdiag;
  mod.method("fun_hc", [](Op const &op) { JULIA_XDIAG_CALL_RETURN(hc(op)) });
  mod.method("fun_hc",
             [](Monomial const &mono) { JULIA_XDIAG_CALL_RETURN(hc(mono)) });
  mod.method("fun_hc",
             [](OpSum const &ops) { JULIA_XDIAG_CALL_RETURN(hc(ops)) });
  mod.method("con_Monomial", []() { JULIA_XDIAG_CALL_RETURN(Monomial()) });
  mod.method("con_Monomial",
             [](Op const &op) { JULIA_XDIAG_CALL_RETURN(Monomial(op)) });
  mod.method("con_Monomial", [](std::vector<Op> const &ops) {
    JULIA_XDIAG_CALL_RETURN(Monomial(ops))
  });
  mod.method("mth_size",
             [](Monomial &self) { JULIA_XDIAG_CALL_RETURN(self.size()) });
  mod.method("mth_empty",
             [](Monomial &self) { JULIA_XDIAG_CALL_RETURN(self.empty()) });
  mod.method("mth_ops",
             [](Monomial &self) { JULIA_XDIAG_CALL_RETURN(self.ops()) });
  mod.method("mth_isreal", [](const Monomial &self) {
    JULIA_XDIAG_CALL_RETURN(self.isreal())
  });
  mod.method("fun_isreal",
             [](Monomial const &m) { JULIA_XDIAG_CALL_RETURN(isreal(m)) });
  mod.method("fun_to_string",
             [](Monomial const &m) { JULIA_XDIAG_CALL_RETURN(to_string(m)) });
  mod.method("con_Op", []() { JULIA_XDIAG_CALL_RETURN(Op()) });
  mod.method("con_Op",
             [](std::string type) { JULIA_XDIAG_CALL_RETURN(Op(type)) });
  mod.method("con_Op", [](std::string type, int64_t site) {
    JULIA_XDIAG_CALL_RETURN(Op(type, site))
  });
  mod.method("con_Op", [](std::string type, std::vector<int64_t> const &sites) {
    JULIA_XDIAG_CALL_RETURN(Op(type, sites))
  });
  mod.method("con_Op", [](std::string type, arma::Col<int64_t> const &sites) {
    JULIA_XDIAG_CALL_RETURN(Op(type, sites))
  });
  mod.method("con_Op",
             [](std::string type, int64_t site, arma::mat const &matrix) {
               JULIA_XDIAG_CALL_RETURN(Op(type, site, matrix))
             });
  mod.method("con_Op", [](std::string type, std::vector<int64_t> const &sites,
                          arma::mat const &matrix) {
    JULIA_XDIAG_CALL_RETURN(Op(type, sites, matrix))
  });
  mod.method("con_Op", [](std::string type, arma::Col<int64_t> const &sites,
                          arma::mat const &matrix) {
    JULIA_XDIAG_CALL_RETURN(Op(type, sites, matrix))
  });
  mod.method("con_Op",
             [](std::string type, int64_t site, arma::cx_mat const &matrix) {
               JULIA_XDIAG_CALL_RETURN(Op(type, site, matrix))
             });
  mod.method("con_Op", [](std::string type, std::vector<int64_t> const &sites,
                          arma::cx_mat const &matrix) {
    JULIA_XDIAG_CALL_RETURN(Op(type, sites, matrix))
  });
  mod.method("con_Op", [](std::string type, arma::Col<int64_t> const &sites,
                          arma::cx_mat const &matrix) {
    JULIA_XDIAG_CALL_RETURN(Op(type, sites, matrix))
  });
  mod.method("mth_type",
             [](const Op &self) { JULIA_XDIAG_CALL_RETURN(self.type()) });
  mod.method("mth_size",
             [](const Op &self) { JULIA_XDIAG_CALL_RETURN(self.size()) });
  mod.method("mth_sites",
             [](const Op &self) { JULIA_XDIAG_CALL_RETURN(self.sites()) });
  mod.method("mth_hassites",
             [](const Op &self) { JULIA_XDIAG_CALL_RETURN(self.hassites()) });
  mod.method("mth_hasmatrix",
             [](const Op &self) { JULIA_XDIAG_CALL_RETURN(self.hasmatrix()) });
  mod.method("mth_isreal",
             [](const Op &self) { JULIA_XDIAG_CALL_RETURN(self.isreal()) });
  mod.method("fun_isreal",
             [](Op const &op) { JULIA_XDIAG_CALL_RETURN(isreal(op)) });
  mod.method("fun_to_string",
             [](Op const &op) { JULIA_XDIAG_CALL_RETURN(to_string(op)) });
  mod.method("con_OpSum", []() { JULIA_XDIAG_CALL_RETURN(OpSum()) });
  mod.method("con_OpSum",
             [](Op const &op) { JULIA_XDIAG_CALL_RETURN(OpSum(op)) });
  mod.method("con_OpSum",
             [](Monomial const &mono) { JULIA_XDIAG_CALL_RETURN(OpSum(mono)) });
  mod.method("con_OpSum", [](std::string const &coeff, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(OpSum(coeff, op))
  });
  mod.method("con_OpSum", [](double coeff, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(OpSum(coeff, op))
  });
  mod.method("con_OpSum", [](complex coeff, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(OpSum(coeff, op))
  });
  mod.method("con_OpSum", [](std::string const &coeff, Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(OpSum(coeff, mono))
  });
  mod.method("con_OpSum", [](double coeff, Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(OpSum(coeff, mono))
  });
  mod.method("con_OpSum", [](complex coeff, Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(OpSum(coeff, mono))
  });
  mod.method("mth_plain",
             [](const OpSum &self) { JULIA_XDIAG_CALL_RETURN(self.plain()) });
  mod.method("mth_size",
             [](OpSum &self) { JULIA_XDIAG_CALL_RETURN(self.size()) });
  mod.method("mth_isreal",
             [](const OpSum &self) { JULIA_XDIAG_CALL_RETURN(self.isreal()) });
  mod.method("mth_empty",
             [](const OpSum &self) { JULIA_XDIAG_CALL_RETURN(self.empty()) });
  mod.method("fun_isreal",
             [](OpSum const &ops) { JULIA_XDIAG_CALL_RETURN(isreal(ops)) });
  mod.method("fun_empty",
             [](OpSum const &ops) { JULIA_XDIAG_CALL_RETURN(empty(ops)) });
  mod.method("fun_to_string",
             [](OpSum const &ops) { JULIA_XDIAG_CALL_RETURN(to_string(ops)) });

  // operator overloads
  mod.method("op_getindex", [](Monomial const &self, int64_t idx) {
    JULIA_XDIAG_CALL_RETURN(self[idx])
  });
  mod.method("op_mul", [](Monomial const &self, Op const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator*(rhs))
  });
  mod.method("op_mul", [](Monomial const &self, Monomial const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator*(rhs))
  });
  mod.method("op_isequal", [](Monomial &self, Monomial const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
  });
  mod.method("op_mul", [](Op const &lhs, Op const &rhs) {
    JULIA_XDIAG_CALL_RETURN(operator*(lhs, rhs))
  });
  mod.method("op_mul", [](Op const &lhs, Monomial const &rhs) {
    JULIA_XDIAG_CALL_RETURN(operator*(lhs, rhs))
  });
  mod.method("op_getindex", [](Op const &self, int64_t idx) {
    JULIA_XDIAG_CALL_RETURN(self[idx])
  });
  mod.method("op_isequal", [](Op const &self, const Op &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
  });
  mod.method("op_add", [](OpSum const &self, OpSum const &ops) {
    JULIA_XDIAG_CALL_RETURN(self.operator+(ops))
  });
  mod.method("op_add", [](OpSum const &self, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(self.operator+(op))
  });
  mod.method("op_add", [](OpSum const &self, Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(self.operator+(mono))
  });
  mod.method("op_sub", [](OpSum const &self, OpSum const &ops) {
    JULIA_XDIAG_CALL_RETURN(self.operator-(ops))
  });
  mod.method("op_sub", [](OpSum const &self, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(self.operator-(op))
  });
  mod.method("op_sub", [](OpSum const &self, Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(self.operator-(mono))
  });
  mod.method("op_sub", [](const OpSum &self) {
    JULIA_XDIAG_CALL_RETURN(self.operator-())
  });
  mod.method("op_mul", [](OpSum const &self, OpSum const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator*(rhs))
  });
  mod.method("op_mul", [](OpSum const &self, Op const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator*(rhs))
  });
  mod.method("op_mul", [](OpSum const &self, Monomial const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator*(rhs))
  });
  mod.method("op_setindex",
             [](OpSum &self, std::string const &name, double const &val) {
               JULIA_XDIAG_CALL_VOID(self[name] = val);
             });
  mod.method("op_setindex",
             [](OpSum &self, std::string const &name, complex const &val) {
               JULIA_XDIAG_CALL_VOID(self[name] = val);
             });
  mod.method("op_isequal", [](OpSum const &self, OpSum const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
  });
  mod.method("op_mul", [](double coeff, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(operator*(coeff, op))
  });
  mod.method("op_mul", [](complex coeff, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(operator*(coeff, op))
  });
  mod.method("op_mul", [](std::string const &coeff, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(operator*(coeff, op))
  });
  mod.method("op_mul", [](Op const &op, double coeff) {
    JULIA_XDIAG_CALL_RETURN(operator*(op, coeff))
  });
  mod.method("op_mul", [](Op const &op, complex coeff) {
    JULIA_XDIAG_CALL_RETURN(operator*(op, coeff))
  });
  mod.method("op_mul", [](Op const &op, std::string const &coeff) {
    JULIA_XDIAG_CALL_RETURN(operator*(op, coeff))
  });
  mod.method("op_mul", [](double coeff, Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(operator*(coeff, mono))
  });
  mod.method("op_mul", [](complex coeff, Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(operator*(coeff, mono))
  });
  mod.method("op_mul", [](std::string const &coeff, Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(operator*(coeff, mono))
  });
  mod.method("op_mul", [](Monomial const &mono, double coeff) {
    JULIA_XDIAG_CALL_RETURN(operator*(mono, coeff))
  });
  mod.method("op_mul", [](Monomial const &mono, complex coeff) {
    JULIA_XDIAG_CALL_RETURN(operator*(mono, coeff))
  });
  mod.method("op_mul", [](Monomial const &mono, std::string const &coeff) {
    JULIA_XDIAG_CALL_RETURN(operator*(mono, coeff))
  });
  mod.method("op_mul", [](double scalar, OpSum const &ops) {
    JULIA_XDIAG_CALL_RETURN(operator*(scalar, ops))
  });
  mod.method("op_mul", [](complex scalar, OpSum const &ops) {
    JULIA_XDIAG_CALL_RETURN(operator*(scalar, ops))
  });
  mod.method("op_mul", [](OpSum const &ops, double scalar) {
    JULIA_XDIAG_CALL_RETURN(operator*(ops, scalar))
  });
  mod.method("op_mul", [](OpSum const &ops, complex scalar) {
    JULIA_XDIAG_CALL_RETURN(operator*(ops, scalar))
  });
  mod.method("op_div", [](OpSum const &ops, double scalar) {
    JULIA_XDIAG_CALL_RETURN(operator/(ops, scalar))
  });
  mod.method("op_div", [](OpSum const &ops, complex scalar) {
    JULIA_XDIAG_CALL_RETURN(operator/(ops, scalar))
  });
  mod.method("op_add", [](Monomial const &lhs, Monomial const &rhs) {
    JULIA_XDIAG_CALL_RETURN(operator+(lhs, rhs))
  });
  mod.method("op_sub", [](Monomial const &lhs, Monomial const &rhs) {
    JULIA_XDIAG_CALL_RETURN(operator-(lhs, rhs))
  });
  mod.method("op_sub", [](Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(operator-(mono))
  });
  mod.method("op_add", [](Monomial const &lhs, OpSum const &rhs) {
    JULIA_XDIAG_CALL_RETURN(operator+(lhs, rhs))
  });
  mod.method("op_sub", [](Monomial const &lhs, OpSum const &rhs) {
    JULIA_XDIAG_CALL_RETURN(operator-(lhs, rhs))
  });
  mod.method("op_mul", [](Op const &lhs, OpSum const &rhs) {
    JULIA_XDIAG_CALL_RETURN(operator*(lhs, rhs))
  });
  mod.method("op_mul", [](Monomial const &lhs, OpSum const &rhs) {
    JULIA_XDIAG_CALL_RETURN(operator*(lhs, rhs))
  });
}
} // namespace xdiag::julia
