// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_submodule.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {
void define_operators(jlcxx::Module &mod) {
  using namespace xdiag;
  mod.method("fun_hc", [](Op const &op) { JULIA_XDIAG_CALL_RETURN(hc(op)) });
  mod.method("fun_hc",
             [](Monomial const &mono) { JULIA_XDIAG_CALL_RETURN(hc(mono)) });
  mod.method("fun_hc",
             [](OpSum const &ops) { JULIA_XDIAG_CALL_RETURN(hc(ops)) });
  mod.method("con_Monomial", []() { JULIA_XDIAG_CALL_RETURN(Monomial()) });
  mod.method("con_Monomial",
             [](Op const &op) { JULIA_XDIAG_CALL_RETURN(Monomial(op)) });
  mod.method("con_Monomial", [](std::vector<Op> const &ops) {
    JULIA_XDIAG_CALL_RETURN(Monomial(ops))
  });
  mod.method("mth_size",
             [](Monomial &self) { JULIA_XDIAG_CALL_RETURN(self.size()) });
  mod.method("mth_empty",
             [](Monomial &self) { JULIA_XDIAG_CALL_RETURN(self.empty()) });
  mod.method("mth_ops",
             [](Monomial &self) { JULIA_XDIAG_CALL_RETURN(self.ops()) });
  mod.method("mth_operator*", [](Monomial &self, Op const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator*(rhs))
  });
  mod.method("mth_operator*", [](Monomial &self, Monomial const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator*(rhs))
  });
  mod.method("mth_operator*=", [](Monomial &self, Op const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator*=(rhs))
  });
  mod.method("mth_operator*=", [](Monomial &self, Monomial const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator*=(rhs))
  });
  mod.method("mth_operator==", [](Monomial &self, Monomial const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
  });
  mod.method("mth_operator!=", [](Monomial &self, Monomial const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator!=(rhs))
  });
  mod.method("mth_operator<", [](Monomial &self, Monomial const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator<(rhs))
  });
  mod.method("mth_isreal",
             [](Monomial &self) { JULIA_XDIAG_CALL_RETURN(self.isreal()) });
  mod.method("fun_operator*", [](Op const &lhs, Op const &rhs) {
    JULIA_XDIAG_CALL_RETURN(operator*(lhs, rhs))
  });
  mod.method("fun_operator*", [](Op const &lhs, Monomial const &rhs) {
    JULIA_XDIAG_CALL_RETURN(operator*(lhs, rhs))
  });
  mod.method("fun_isreal",
             [](Monomial const &m) { JULIA_XDIAG_CALL_RETURN(isreal(m)) });
  mod.method("fun_to_string",
             [](Monomial const &m) { JULIA_XDIAG_CALL_RETURN(to_string(m)) });
  mod.method("con_Op", []() { JULIA_XDIAG_CALL_RETURN(Op()) });
  mod.method("con_Op",
             [](std::string type) { JULIA_XDIAG_CALL_RETURN(Op(type)) });
  mod.method("con_Op", [](std::string type, int64_t site) {
    JULIA_XDIAG_CALL_RETURN(Op(type, site))
  });
  mod.method("con_Op", [](std::string type, std::vector<int64_t> const &sites) {
    JULIA_XDIAG_CALL_RETURN(Op(type, sites))
  });
  mod.method("con_Op",
             [](std::string type, int64_t site, arma::mat const &matrix) {
               JULIA_XDIAG_CALL_RETURN(Op(type, site, matrix))
             });
  mod.method("con_Op", [](std::string type, std::vector<int64_t> const &sites,
                          arma::mat const &matrix) {
    JULIA_XDIAG_CALL_RETURN(Op(type, sites, matrix))
  });
  mod.method("con_Op",
             [](std::string type, int64_t site, arma::cx_mat const &matrix) {
               JULIA_XDIAG_CALL_RETURN(Op(type, site, matrix))
             });
  mod.method("con_Op", [](std::string type, std::vector<int64_t> const &sites,
                          arma::cx_mat const &matrix) {
    JULIA_XDIAG_CALL_RETURN(Op(type, sites, matrix))
  });
  mod.method("mth_type",
             [](const Op &self) { JULIA_XDIAG_CALL_RETURN(self.type()) });
  mod.method("mth_size",
             [](const Op &self) { JULIA_XDIAG_CALL_RETURN(self.size()) });
  mod.method("mth_sites",
             [](const Op &self) { JULIA_XDIAG_CALL_RETURN(self.sites()) });
  mod.method("mth_hassites",
             [](const Op &self) { JULIA_XDIAG_CALL_RETURN(self.hassites()) });
  mod.method("mth_hasmatrix",
             [](const Op &self) { JULIA_XDIAG_CALL_RETURN(self.hasmatrix()) });
  mod.method("mth_isreal",
             [](const Op &self) { JULIA_XDIAG_CALL_RETURN(self.isreal()) });
  mod.method("mth_operator==", [](Op const &self, const Op &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
  });
  mod.method("mth_operator!=", [](Op const &self, const Op &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator!=(rhs))
  });
  mod.method("mth_operator<", [](Op &self, const Op &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator<(rhs))
  });
  mod.method("fun_isreal",
             [](Op const &op) { JULIA_XDIAG_CALL_RETURN(isreal(op)) });
  mod.method("fun_to_string",
             [](Op const &op) { JULIA_XDIAG_CALL_RETURN(to_string(op)) });
  mod.method("con_OpSum", []() { JULIA_XDIAG_CALL_RETURN(OpSum()) });
  mod.method("con_OpSum",
             [](Op const &op) { JULIA_XDIAG_CALL_RETURN(OpSum(op)) });
  mod.method("con_OpSum",
             [](Monomial const &mono) { JULIA_XDIAG_CALL_RETURN(OpSum(mono)) });
  mod.method("con_OpSum", [](std::string const &coeff, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(OpSum(coeff, op))
  });
  mod.method("con_OpSum", [](double coeff, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(OpSum(coeff, op))
  });
  mod.method("con_OpSum", [](complex coeff, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(OpSum(coeff, op))
  });
  mod.method("con_OpSum", [](std::string const &coeff, Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(OpSum(coeff, mono))
  });
  mod.method("con_OpSum", [](double coeff, Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(OpSum(coeff, mono))
  });
  mod.method("con_OpSum", [](complex coeff, Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(OpSum(coeff, mono))
  });
  mod.method("mth_operator+=", [](OpSum &self, OpSum const &ops) {
    JULIA_XDIAG_CALL_RETURN(self.operator+=(ops))
  });
  mod.method("mth_operator+=", [](OpSum &self, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(self.operator+=(op))
  });
  mod.method("mth_operator+=", [](OpSum &self, Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(self.operator+=(mono))
  });
  mod.method("mth_operator+", [](OpSum const &self, OpSum const &ops) {
    JULIA_XDIAG_CALL_RETURN(self.operator+(ops))
  });
  mod.method("mth_operator+", [](OpSum const &self, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(self.operator+(op))
  });
  mod.method("mth_operator+", [](OpSum const &self, Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(self.operator+(mono))
  });
  mod.method("mth_operator-=", [](OpSum &self, OpSum const &ops) {
    JULIA_XDIAG_CALL_RETURN(self.operator-=(ops))
  });
  mod.method("mth_operator-=", [](OpSum &self, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(self.operator-=(op))
  });
  mod.method("mth_operator-=", [](OpSum &self, Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(self.operator-=(mono))
  });
  mod.method("mth_operator-", [](OpSum const &self, OpSum const &ops) {
    JULIA_XDIAG_CALL_RETURN(self.operator-(ops))
  });
  mod.method("mth_operator-", [](OpSum const &self, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(self.operator-(op))
  });
  mod.method("mth_operator-", [](OpSum const &self, Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(self.operator-(mono))
  });
  mod.method("mth_operator-", [](const OpSum &self) {
    JULIA_XDIAG_CALL_RETURN(self.operator-())
  });
  mod.method("mth_operator*=", [](OpSum &self, double scalar) {
    JULIA_XDIAG_CALL_RETURN(self.operator*=(scalar))
  });
  mod.method("mth_operator*=", [](OpSum &self, complex scalar) {
    JULIA_XDIAG_CALL_RETURN(self.operator*=(scalar))
  });
  mod.method("mth_operator/=", [](OpSum &self, double scalar) {
    JULIA_XDIAG_CALL_RETURN(self.operator/=(scalar))
  });
  mod.method("mth_operator/=", [](OpSum &self, complex scalar) {
    JULIA_XDIAG_CALL_RETURN(self.operator/=(scalar))
  });
  mod.method("mth_operator*", [](OpSum const &self, OpSum const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator*(rhs))
  });
  mod.method("mth_operator*=", [](OpSum &self, OpSum const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator*=(rhs))
  });
  mod.method("mth_operator*", [](OpSum const &self, Op const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator*(rhs))
  });
  mod.method("mth_operator*=", [](OpSum &self, Op const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator*=(rhs))
  });
  mod.method("mth_operator*", [](OpSum const &self, Monomial const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator*(rhs))
  });
  mod.method("mth_operator*=", [](OpSum &self, Monomial const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator*=(rhs))
  });
  mod.method("mth_plain",
             [](const OpSum &self) { JULIA_XDIAG_CALL_RETURN(self.plain()) });
  mod.method("mth_size",
             [](OpSum &self) { JULIA_XDIAG_CALL_RETURN(self.size()) });
  mod.method("mth_operator==", [](OpSum const &self, OpSum const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
  });
  mod.method("mth_operator!=", [](OpSum const &self, OpSum const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator!=(rhs))
  });
  mod.method("mth_isreal",
             [](const OpSum &self) { JULIA_XDIAG_CALL_RETURN(self.isreal()) });
  mod.method("mth_empty",
             [](const OpSum &self) { JULIA_XDIAG_CALL_RETURN(self.empty()) });
  mod.method("fun_operator*", [](double coeff, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(operator*(coeff, op))
  });
  mod.method("fun_operator*", [](complex coeff, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(operator*(coeff, op))
  });
  mod.method("fun_operator*", [](std::string const &coeff, Op const &op) {
    JULIA_XDIAG_CALL_RETURN(operator*(coeff, op))
  });
  mod.method("fun_operator*", [](Op const &op, double coeff) {
    JULIA_XDIAG_CALL_RETURN(operator*(op, coeff))
  });
  mod.method("fun_operator*", [](Op const &op, complex coeff) {
    JULIA_XDIAG_CALL_RETURN(operator*(op, coeff))
  });
  mod.method("fun_operator*", [](Op const &op, std::string const &coeff) {
    JULIA_XDIAG_CALL_RETURN(operator*(op, coeff))
  });
  mod.method("fun_operator*", [](double coeff, Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(operator*(coeff, mono))
  });
  mod.method("fun_operator*", [](complex coeff, Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(operator*(coeff, mono))
  });
  mod.method("fun_operator*",
             [](std::string const &coeff, Monomial const &mono) {
               JULIA_XDIAG_CALL_RETURN(operator*(coeff, mono))
             });
  mod.method("fun_operator*", [](Monomial const &mono, double coeff) {
    JULIA_XDIAG_CALL_RETURN(operator*(mono, coeff))
  });
  mod.method("fun_operator*", [](Monomial const &mono, complex coeff) {
    JULIA_XDIAG_CALL_RETURN(operator*(mono, coeff))
  });
  mod.method("fun_operator*",
             [](Monomial const &mono, std::string const &coeff) {
               JULIA_XDIAG_CALL_RETURN(operator*(mono, coeff))
             });
  mod.method("fun_operator*", [](double scalar, OpSum const &ops) {
    JULIA_XDIAG_CALL_RETURN(operator*(scalar, ops))
  });
  mod.method("fun_operator*", [](complex scalar, OpSum const &ops) {
    JULIA_XDIAG_CALL_RETURN(operator*(scalar, ops))
  });
  mod.method("fun_operator*", [](OpSum const &ops, double scalar) {
    JULIA_XDIAG_CALL_RETURN(operator*(ops, scalar))
  });
  mod.method("fun_operator*", [](OpSum const &ops, complex scalar) {
    JULIA_XDIAG_CALL_RETURN(operator*(ops, scalar))
  });
  mod.method("fun_operator/", [](OpSum const &ops, double scalar) {
    JULIA_XDIAG_CALL_RETURN(operator/(ops, scalar))
  });
  mod.method("fun_operator/", [](OpSum const &ops, complex scalar) {
    JULIA_XDIAG_CALL_RETURN(operator/(ops, scalar))
  });
  mod.method("fun_operator+", [](Monomial const &lhs, Monomial const &rhs) {
    JULIA_XDIAG_CALL_RETURN(operator+(lhs, rhs))
  });
  mod.method("fun_operator-", [](Monomial const &lhs, Monomial const &rhs) {
    JULIA_XDIAG_CALL_RETURN(operator-(lhs, rhs))
  });
  mod.method("fun_operator-", [](Monomial const &mono) {
    JULIA_XDIAG_CALL_RETURN(operator-(mono))
  });
  mod.method("fun_operator+", [](Monomial const &lhs, OpSum const &rhs) {
    JULIA_XDIAG_CALL_RETURN(operator+(lhs, rhs))
  });
  mod.method("fun_operator-", [](Monomial const &lhs, OpSum const &rhs) {
    JULIA_XDIAG_CALL_RETURN(operator-(lhs, rhs))
  });
  mod.method("fun_operator*", [](Op const &lhs, OpSum const &rhs) {
    JULIA_XDIAG_CALL_RETURN(operator*(lhs, rhs))
  });
  mod.method("fun_operator*", [](Monomial const &lhs, OpSum const &rhs) {
    JULIA_XDIAG_CALL_RETURN(operator*(lhs, rhs))
  });
  mod.method("fun_isreal",
             [](OpSum const &ops) { JULIA_XDIAG_CALL_RETURN(isreal(ops)) });
  mod.method("fun_empty",
             [](OpSum const &ops) { JULIA_XDIAG_CALL_RETURN(empty(ops)) });
  mod.method("fun_to_string",
             [](OpSum const &ops) { JULIA_XDIAG_CALL_RETURN(to_string(ops)) });
}
} // namespace xdiag::julia
