// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_submodule.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {
void define_random(jlcxx::Module &mod) {
  using namespace xdiag;

  // operator overloads
}
} // namespace xdiag::julia
