// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_submodule.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {
void define_states(jlcxx::Module &mod) {
  using namespace xdiag;
  mod.method("fun_apply", [](Op const &op, State const &v) {
    JULIA_XDIAG_CALL_RETURN(apply(op, v))
  });
  mod.method("fun_apply", [](Monomial const &mono, State const &v) {
    JULIA_XDIAG_CALL_RETURN(apply(mono, v))
  });
  mod.method("fun_apply", [](OpSum const &ops, State const &v) {
    JULIA_XDIAG_CALL_RETURN(apply(ops, v))
  });
  mod.method("fun_apply", [](Op const &op, State const &v, State &w) {
    JULIA_XDIAG_CALL_VOID(apply(op, v, w));
  });
  mod.method("fun_apply", [](Monomial const &mono, State const &v, State &w) {
    JULIA_XDIAG_CALL_VOID(apply(mono, v, w));
  });
  mod.method("fun_apply", [](OpSum const &ops, State const &v, State &w) {
    JULIA_XDIAG_CALL_VOID(apply(ops, v, w));
  });
  mod.method("fun_correlation_matrix",
             [](State const &state, std::string type1, std::string type2) {
               JULIA_XDIAG_CALL_RETURN(correlation_matrix(state, type1, type2))
             });
  mod.method("fun_correlation_matrixC",
             [](State const &state, std::string type1, std::string type2) {
               JULIA_XDIAG_CALL_RETURN(correlation_matrixC(state, type1, type2))
             });
  mod.method("fun_product_state",
             [](Fermion const &block, std::vector<int32_t> const &local_state,
                bool real = true) {
               JULIA_XDIAG_CALL_RETURN(product_state(block, local_state, true))
             });
  mod.method("fun_product_state",
             [](Boson const &block, std::vector<int32_t> const &local_state,
                bool real = true) {
               JULIA_XDIAG_CALL_RETURN(product_state(block, local_state, true))
             });
  mod.method("fun_product_state",
             [](Spinhalf const &block, std::vector<int32_t> const &local_state,
                bool real = true) {
               JULIA_XDIAG_CALL_RETURN(product_state(block, local_state, true))
             });
  mod.method("fun_product_state",
             [](Electron const &block, std::vector<int32_t> const &local_state,
                bool real = true) {
               JULIA_XDIAG_CALL_RETURN(product_state(block, local_state, true))
             });
  mod.method("fun_product_state",
             [](tJ const &block, std::vector<int32_t> const &local_state,
                bool real = true) {
               JULIA_XDIAG_CALL_RETURN(product_state(block, local_state, true))
             });
  mod.method("fun_product_state",
             [](Fermion const &block, std::vector<int64_t> const &local_state,
                bool real = true) {
               JULIA_XDIAG_CALL_RETURN(product_state(block, local_state, true))
             });
  mod.method("fun_product_state",
             [](Boson const &block, std::vector<int64_t> const &local_state,
                bool real = true) {
               JULIA_XDIAG_CALL_RETURN(product_state(block, local_state, true))
             });
  mod.method("fun_product_state",
             [](Spinhalf const &block, std::vector<int64_t> const &local_state,
                bool real = true) {
               JULIA_XDIAG_CALL_RETURN(product_state(block, local_state, true))
             });
  mod.method("fun_product_state",
             [](Electron const &block, std::vector<int64_t> const &local_state,
                bool real = true) {
               JULIA_XDIAG_CALL_RETURN(product_state(block, local_state, true))
             });
  mod.method("fun_product_state",
             [](tJ const &block, std::vector<int64_t> const &local_state,
                bool real = true) {
               JULIA_XDIAG_CALL_RETURN(product_state(block, local_state, true))
             });
  mod.method("fun_random_state",
             [](Fermion const &block, bool real = true, int64_t ncols = 1,
                int64_t seed = 42, bool normalized = true) {
               JULIA_XDIAG_CALL_RETURN(random_state(block, true, 1, 42, true))
             });
  mod.method("fun_random_state",
             [](Boson const &block, bool real = true, int64_t ncols = 1,
                int64_t seed = 42, bool normalized = true) {
               JULIA_XDIAG_CALL_RETURN(random_state(block, true, 1, 42, true))
             });
  mod.method("fun_random_state",
             [](Spinhalf const &block, bool real = true, int64_t ncols = 1,
                int64_t seed = 42, bool normalized = true) {
               JULIA_XDIAG_CALL_RETURN(random_state(block, true, 1, 42, true))
             });
  mod.method("fun_random_state",
             [](Electron const &block, bool real = true, int64_t ncols = 1,
                int64_t seed = 42, bool normalized = true) {
               JULIA_XDIAG_CALL_RETURN(random_state(block, true, 1, 42, true))
             });
  mod.method("fun_random_state",
             [](tJ const &block, bool real = true, int64_t ncols = 1,
                int64_t seed = 42, bool normalized = true) {
               JULIA_XDIAG_CALL_RETURN(random_state(block, true, 1, 42, true))
             });
  mod.method("fun_zero_state",
             [](Fermion const &block, bool real = true, int64_t ncols = 1) {
               JULIA_XDIAG_CALL_RETURN(zero_state(block, true, 1))
             });
  mod.method("fun_zero_state",
             [](Boson const &block, bool real = true, int64_t ncols = 1) {
               JULIA_XDIAG_CALL_RETURN(zero_state(block, true, 1))
             });
  mod.method("fun_zero_state",
             [](Spinhalf const &block, bool real = true, int64_t ncols = 1) {
               JULIA_XDIAG_CALL_RETURN(zero_state(block, true, 1))
             });
  mod.method("fun_zero_state",
             [](Electron const &block, bool real = true, int64_t ncols = 1) {
               JULIA_XDIAG_CALL_RETURN(zero_state(block, true, 1))
             });
  mod.method("fun_zero_state",
             [](tJ const &block, bool real = true, int64_t ncols = 1) {
               JULIA_XDIAG_CALL_RETURN(zero_state(block, true, 1))
             });
  mod.method("fun_zero",
             [](State &state) { JULIA_XDIAG_CALL_VOID(zero(state)); });
  mod.method("fun_dot", [](State const &v, State const &w) {
    JULIA_XDIAG_CALL_RETURN(dot(v, w))
  });
  mod.method("fun_dotC", [](State const &v, State const &w) {
    JULIA_XDIAG_CALL_RETURN(dotC(v, w))
  });
  mod.method("fun_matrix_dot", [](State const &v, State const &w) {
    JULIA_XDIAG_CALL_RETURN(matrix_dot(v, w))
  });
  mod.method("fun_matrix_dotC", [](State const &v, State const &w) {
    JULIA_XDIAG_CALL_RETURN(matrix_dotC(v, w))
  });
  mod.method("fun_expect", [](State const &state, std::string type) {
    JULIA_XDIAG_CALL_RETURN(expect(state, type))
  });
  mod.method("fun_expectC", [](State const &state, std::string type) {
    JULIA_XDIAG_CALL_RETURN(expectC(state, type))
  });
  mod.method("fun_inner", [](Op const &A, State const &v) {
    JULIA_XDIAG_CALL_RETURN(inner(A, v))
  });
  mod.method("fun_inner", [](Monomial const &A, State const &v) {
    JULIA_XDIAG_CALL_RETURN(inner(A, v))
  });
  mod.method("fun_inner", [](OpSum const &A, State const &v) {
    JULIA_XDIAG_CALL_RETURN(inner(A, v))
  });
  mod.method("fun_innerC", [](Op const &A, State const &w) {
    JULIA_XDIAG_CALL_RETURN(innerC(A, w))
  });
  mod.method("fun_innerC", [](Monomial const &A, State const &w) {
    JULIA_XDIAG_CALL_RETURN(innerC(A, w))
  });
  mod.method("fun_innerC", [](OpSum const &A, State const &w) {
    JULIA_XDIAG_CALL_RETURN(innerC(A, w))
  });
  mod.method("fun_inner", [](State const &v, Op const &A, State const &w) {
    JULIA_XDIAG_CALL_RETURN(inner(v, A, w))
  });
  mod.method("fun_inner",
             [](State const &v, Monomial const &A, State const &w) {
               JULIA_XDIAG_CALL_RETURN(inner(v, A, w))
             });
  mod.method("fun_inner", [](State const &v, OpSum const &A, State const &w) {
    JULIA_XDIAG_CALL_RETURN(inner(v, A, w))
  });
  mod.method("fun_innerC", [](State const &v, Op const &A, State const &w) {
    JULIA_XDIAG_CALL_RETURN(innerC(v, A, w))
  });
  mod.method("fun_innerC",
             [](State const &v, Monomial const &A, State const &w) {
               JULIA_XDIAG_CALL_RETURN(innerC(v, A, w))
             });
  mod.method("fun_innerC", [](State const &v, OpSum const &A, State const &w) {
    JULIA_XDIAG_CALL_RETURN(innerC(v, A, w))
  });
  mod.method("fun_norm",
             [](State const &v) { JULIA_XDIAG_CALL_RETURN(norm(v)) });
  mod.method("fun_norm1",
             [](State const &v) { JULIA_XDIAG_CALL_RETURN(norm1(v)) });
  mod.method("fun_norminf",
             [](State const &v) { JULIA_XDIAG_CALL_RETURN(norminf(v)) });
  mod.method("con_ProductState",
             []() { JULIA_XDIAG_CALL_RETURN(ProductState()) });
  mod.method("con_ProductState", [](int64_t nsites) {
    JULIA_XDIAG_CALL_RETURN(ProductState(nsites))
  });
  mod.method("con_ProductState", [](std::vector<int32_t> const &local_states) {
    JULIA_XDIAG_CALL_RETURN(ProductState(local_states))
  });
  mod.method("con_ProductState", [](std::vector<int64_t> const &local_states) {
    JULIA_XDIAG_CALL_RETURN(ProductState(local_states))
  });
  mod.method("mth_size", [](const ProductState &self) {
    JULIA_XDIAG_CALL_RETURN(self.size())
  });
  mod.method("mth_nsites", [](const ProductState &self) {
    JULIA_XDIAG_CALL_RETURN(self.nsites())
  });
  mod.method("mth_push_back", [](ProductState &self, int64_t l) {
    JULIA_XDIAG_CALL_VOID(self.push_back(l));
  });
  mod.method("mth_operator==",
             [](ProductState const &self, ProductState const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
             });
  mod.method("mth_operator!=",
             [](ProductState const &self, ProductState const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator!=(rhs))
             });
  mod.method("fun_size",
             [](ProductState const &p) { JULIA_XDIAG_CALL_RETURN(size(p)) });
  mod.method("fun_nsites",
             [](ProductState const &p) { JULIA_XDIAG_CALL_RETURN(nsites(p)) });
  mod.method("fun_to_string", [](ProductState const &state) {
    JULIA_XDIAG_CALL_RETURN(to_string(state))
  });
  mod.method("con_RandomState", [](int64_t seed = 42, bool normalized = true) {
    JULIA_XDIAG_CALL_RETURN(RandomState(42, true))
  });
  mod.method("mth_seed", [](const RandomState &self) {
    JULIA_XDIAG_CALL_RETURN(self.seed())
  });
  mod.method("mth_normalized", [](const RandomState &self) {
    JULIA_XDIAG_CALL_RETURN(self.normalized())
  });
  mod.method("fun_to_string", [](RandomState const &state) {
    JULIA_XDIAG_CALL_RETURN(to_string(state))
  });
  mod.method("con_State", []() { JULIA_XDIAG_CALL_RETURN(State()) });
  mod.method("con_State",
             [](Fermion const &block, bool real = true, int64_t ncols = 1) {
               JULIA_XDIAG_CALL_RETURN(State(block, true, 1))
             });
  mod.method("con_State",
             [](Boson const &block, bool real = true, int64_t ncols = 1) {
               JULIA_XDIAG_CALL_RETURN(State(block, true, 1))
             });
  mod.method("con_State",
             [](Spinhalf const &block, bool real = true, int64_t ncols = 1) {
               JULIA_XDIAG_CALL_RETURN(State(block, true, 1))
             });
  mod.method("con_State",
             [](Electron const &block, bool real = true, int64_t ncols = 1) {
               JULIA_XDIAG_CALL_RETURN(State(block, true, 1))
             });
  mod.method("con_State",
             [](tJ const &block, bool real = true, int64_t ncols = 1) {
               JULIA_XDIAG_CALL_RETURN(State(block, true, 1))
             });
  mod.method("con_State", [](Fermion const &block, arma::vec const &vector) {
    JULIA_XDIAG_CALL_RETURN(State(block, vector))
  });
  mod.method("con_State", [](Boson const &block, arma::vec const &vector) {
    JULIA_XDIAG_CALL_RETURN(State(block, vector))
  });
  mod.method("con_State", [](Spinhalf const &block, arma::vec const &vector) {
    JULIA_XDIAG_CALL_RETURN(State(block, vector))
  });
  mod.method("con_State", [](Electron const &block, arma::vec const &vector) {
    JULIA_XDIAG_CALL_RETURN(State(block, vector))
  });
  mod.method("con_State", [](tJ const &block, arma::vec const &vector) {
    JULIA_XDIAG_CALL_RETURN(State(block, vector))
  });
  mod.method("con_State", [](Fermion const &block, arma::cx_vec const &vector) {
    JULIA_XDIAG_CALL_RETURN(State(block, vector))
  });
  mod.method("con_State", [](Boson const &block, arma::cx_vec const &vector) {
    JULIA_XDIAG_CALL_RETURN(State(block, vector))
  });
  mod.method("con_State",
             [](Spinhalf const &block, arma::cx_vec const &vector) {
               JULIA_XDIAG_CALL_RETURN(State(block, vector))
             });
  mod.method("con_State",
             [](Electron const &block, arma::cx_vec const &vector) {
               JULIA_XDIAG_CALL_RETURN(State(block, vector))
             });
  mod.method("con_State", [](tJ const &block, arma::cx_vec const &vector) {
    JULIA_XDIAG_CALL_RETURN(State(block, vector))
  });
  mod.method("con_State", [](Fermion const &block, arma::mat const &matrix) {
    JULIA_XDIAG_CALL_RETURN(State(block, matrix))
  });
  mod.method("con_State", [](Boson const &block, arma::mat const &matrix) {
    JULIA_XDIAG_CALL_RETURN(State(block, matrix))
  });
  mod.method("con_State", [](Spinhalf const &block, arma::mat const &matrix) {
    JULIA_XDIAG_CALL_RETURN(State(block, matrix))
  });
  mod.method("con_State", [](Electron const &block, arma::mat const &matrix) {
    JULIA_XDIAG_CALL_RETURN(State(block, matrix))
  });
  mod.method("con_State", [](tJ const &block, arma::mat const &matrix) {
    JULIA_XDIAG_CALL_RETURN(State(block, matrix))
  });
  mod.method("con_State", [](Fermion const &block, arma::cx_mat const &matrix) {
    JULIA_XDIAG_CALL_RETURN(State(block, matrix))
  });
  mod.method("con_State", [](Boson const &block, arma::cx_mat const &matrix) {
    JULIA_XDIAG_CALL_RETURN(State(block, matrix))
  });
  mod.method("con_State",
             [](Spinhalf const &block, arma::cx_mat const &matrix) {
               JULIA_XDIAG_CALL_RETURN(State(block, matrix))
             });
  mod.method("con_State",
             [](Electron const &block, arma::cx_mat const &matrix) {
               JULIA_XDIAG_CALL_RETURN(State(block, matrix))
             });
  mod.method("con_State", [](tJ const &block, arma::cx_mat const &matrix) {
    JULIA_XDIAG_CALL_RETURN(State(block, matrix))
  });
  mod.method("mth_isvalid",
             [](const State &self) { JULIA_XDIAG_CALL_RETURN(self.isvalid()) });
  mod.method("mth_nsites",
             [](const State &self) { JULIA_XDIAG_CALL_RETURN(self.nsites()) });
  mod.method("mth_isreal",
             [](const State &self) { JULIA_XDIAG_CALL_RETURN(self.isreal()) });
  mod.method("mth_real",
             [](const State &self) { JULIA_XDIAG_CALL_RETURN(self.real()) });
  mod.method("mth_imag",
             [](const State &self) { JULIA_XDIAG_CALL_RETURN(self.imag()) });
  mod.method("mth_make_complex",
             [](State &self) { JULIA_XDIAG_CALL_VOID(self.make_complex()); });
  mod.method("mth_dim",
             [](const State &self) { JULIA_XDIAG_CALL_RETURN(self.dim()) });
  mod.method("mth_size",
             [](const State &self) { JULIA_XDIAG_CALL_RETURN(self.size()) });
  mod.method("mth_nrows",
             [](const State &self) { JULIA_XDIAG_CALL_RETURN(self.nrows()) });
  mod.method("mth_ncols",
             [](const State &self) { JULIA_XDIAG_CALL_RETURN(self.ncols()) });
  mod.method("mth_col", [](State const &self, int64_t n, bool copy = true) {
    JULIA_XDIAG_CALL_RETURN(self.col(n, true))
  });
  mod.method("mth_vector",
             [](State const &self, int64_t n = 0, bool copy = true) {
               JULIA_XDIAG_CALL_RETURN(self.vector(0, true))
             });
  mod.method("mth_matrix", [](State const &self, bool copy = true) {
    JULIA_XDIAG_CALL_RETURN(self.matrix(true))
  });
  mod.method("mth_vectorC",
             [](State const &self, int64_t n = 0, bool copy = true) {
               JULIA_XDIAG_CALL_RETURN(self.vectorC(0, true))
             });
  mod.method("mth_matrixC", [](State const &self, bool copy = true) {
    JULIA_XDIAG_CALL_RETURN(self.matrixC(true))
  });
  mod.method("con_State", [](Fermion const &block, double const *ptr,
                             int64_t ncols, int64_t stride = 1) {
    JULIA_XDIAG_CALL_RETURN(State(block, ptr, ncols, 1))
  });
  mod.method("con_State", [](Boson const &block, double const *ptr,
                             int64_t ncols, int64_t stride = 1) {
    JULIA_XDIAG_CALL_RETURN(State(block, ptr, ncols, 1))
  });
  mod.method("con_State", [](Spinhalf const &block, double const *ptr,
                             int64_t ncols, int64_t stride = 1) {
    JULIA_XDIAG_CALL_RETURN(State(block, ptr, ncols, 1))
  });
  mod.method("con_State", [](Electron const &block, double const *ptr,
                             int64_t ncols, int64_t stride = 1) {
    JULIA_XDIAG_CALL_RETURN(State(block, ptr, ncols, 1))
  });
  mod.method("con_State", [](tJ const &block, double const *ptr, int64_t ncols,
                             int64_t stride = 1) {
    JULIA_XDIAG_CALL_RETURN(State(block, ptr, ncols, 1))
  });
  mod.method("con_State",
             [](Fermion const &block, complex const *ptr, int64_t ncols) {
               JULIA_XDIAG_CALL_RETURN(State(block, ptr, ncols))
             });
  mod.method("con_State",
             [](Boson const &block, complex const *ptr, int64_t ncols) {
               JULIA_XDIAG_CALL_RETURN(State(block, ptr, ncols))
             });
  mod.method("con_State",
             [](Spinhalf const &block, complex const *ptr, int64_t ncols) {
               JULIA_XDIAG_CALL_RETURN(State(block, ptr, ncols))
             });
  mod.method("con_State",
             [](Electron const &block, complex const *ptr, int64_t ncols) {
               JULIA_XDIAG_CALL_RETURN(State(block, ptr, ncols))
             });
  mod.method("con_State",
             [](tJ const &block, complex const *ptr, int64_t ncols) {
               JULIA_XDIAG_CALL_RETURN(State(block, ptr, ncols))
             });
  mod.method("mth_memptr",
             [](State &self) { JULIA_XDIAG_CALL_RETURN(self.memptr()) });
  mod.method("mth_memptrC",
             [](State &self) { JULIA_XDIAG_CALL_RETURN(self.memptrC()) });
  mod.method("mth_colptr", [](State &self, int64_t col) {
    JULIA_XDIAG_CALL_RETURN(self.colptr(col))
  });
  mod.method("mth_colptrC", [](State &self, int64_t col) {
    JULIA_XDIAG_CALL_RETURN(self.colptrC(col))
  });
  mod.method("fun_isvalid",
             [](State const &s) { JULIA_XDIAG_CALL_RETURN(isvalid(s)) });
  mod.method("fun_nsites",
             [](State const &s) { JULIA_XDIAG_CALL_RETURN(nsites(s)) });
  mod.method("fun_isapprox", [](State const &v, State const &w,
                                double rtol = 1e-12, double atol = 1e-12) {
    JULIA_XDIAG_CALL_RETURN(isapprox(v, w, 1e-12, 1e-12))
  });
  mod.method("fun_isreal",
             [](State const &s) { JULIA_XDIAG_CALL_RETURN(isreal(s)) });
  mod.method("fun_real",
             [](State const &s) { JULIA_XDIAG_CALL_RETURN(real(s)) });
  mod.method("fun_imag",
             [](State const &s) { JULIA_XDIAG_CALL_RETURN(imag(s)) });
  mod.method("fun_make_complex",
             [](State &s) { JULIA_XDIAG_CALL_VOID(make_complex(s)); });
  mod.method("fun_dim", [](State const &s) { JULIA_XDIAG_CALL_RETURN(dim(s)) });
  mod.method("fun_size",
             [](State const &s) { JULIA_XDIAG_CALL_RETURN(size(s)) });
  mod.method("fun_nrows",
             [](State const &s) { JULIA_XDIAG_CALL_RETURN(nrows(s)) });
  mod.method("fun_ncols",
             [](State const &s) { JULIA_XDIAG_CALL_RETURN(ncols(s)) });
  mod.method("fun_col", [](State const &s, int64_t n, bool copy = true) {
    JULIA_XDIAG_CALL_RETURN(col(s, n, true))
  });
  mod.method("fun_vector", [](State const &s, int64_t n = 0, bool copy = true) {
    JULIA_XDIAG_CALL_RETURN(vector(s, 0, true))
  });
  mod.method("fun_matrix", [](State const &s, bool copy = true) {
    JULIA_XDIAG_CALL_RETURN(matrix(s, true))
  });
  mod.method("fun_vectorC",
             [](State const &s, int64_t n = 0, bool copy = true) {
               JULIA_XDIAG_CALL_RETURN(vectorC(s, 0, true))
             });
  mod.method("fun_matrixC", [](State const &s, bool copy = true) {
    JULIA_XDIAG_CALL_RETURN(matrixC(s, true))
  });
  mod.method("fun_to_string", [](State const &state) {
    JULIA_XDIAG_CALL_RETURN(to_string(state))
  });
  mod.method("fun_operator*=", [](State &X, double alpha) {
    JULIA_XDIAG_CALL_RETURN(operator*=(X, alpha))
  });
  mod.method("fun_operator*", [](State const &X, double alpha) {
    JULIA_XDIAG_CALL_RETURN(operator*(X, alpha))
  });
  mod.method("fun_operator*", [](double alpha, State const &X) {
    JULIA_XDIAG_CALL_RETURN(operator*(alpha, X))
  });
  mod.method("fun_operator*=", [](State &X, complex alpha) {
    JULIA_XDIAG_CALL_RETURN(operator*=(X, alpha))
  });
  mod.method("fun_operator*", [](State const &X, complex alpha) {
    JULIA_XDIAG_CALL_RETURN(operator*(X, alpha))
  });
  mod.method("fun_operator*", [](complex alpha, State const &X) {
    JULIA_XDIAG_CALL_RETURN(operator*(alpha, X))
  });
  mod.method("fun_operator/=", [](State &X, double alpha) {
    JULIA_XDIAG_CALL_RETURN(operator/=(X, alpha))
  });
  mod.method("fun_operator/", [](State const &X, double alpha) {
    JULIA_XDIAG_CALL_RETURN(operator/(X, alpha))
  });
  mod.method("fun_operator/=", [](State &X, complex alpha) {
    JULIA_XDIAG_CALL_RETURN(operator/=(X, alpha))
  });
  mod.method("fun_operator/", [](State const &X, complex alpha) {
    JULIA_XDIAG_CALL_RETURN(operator/(X, alpha))
  });
  mod.method("fun_operator+=", [](State &v, State const &w) {
    JULIA_XDIAG_CALL_RETURN(operator+=(v, w))
  });
  mod.method("fun_operator-=", [](State &v, State const &w) {
    JULIA_XDIAG_CALL_RETURN(operator-=(v, w))
  });
  mod.method("fun_operator+", [](State const &v, State const &w) {
    JULIA_XDIAG_CALL_RETURN(operator+(v, w))
  });
  mod.method("fun_operator-", [](State const &v, State const &w) {
    JULIA_XDIAG_CALL_RETURN(operator-(v, w))
  });
  mod.method("fun_operator-",
             [](State const &v) { JULIA_XDIAG_CALL_RETURN(operator-(v)) });
}
} // namespace xdiag::julia
