// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_submodule.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {
void define_symmetries(jlcxx::Module &mod) {
  using namespace xdiag;
  mod.method("con_Permutation",
             []() { JULIA_XDIAG_CALL_RETURN(Permutation()) });
  mod.method("con_Permutation",
             [](int64_t size) { JULIA_XDIAG_CALL_RETURN(Permutation(size)) });
  mod.method("con_Permutation", [](std::initializer_list<int64_t> list) {
    JULIA_XDIAG_CALL_RETURN(Permutation(list))
  });
  mod.method("con_Permutation", [](std::vector<int32_t> const &array) {
    JULIA_XDIAG_CALL_RETURN(Permutation(array))
  });
  mod.method("con_Permutation", [](std::vector<int64_t> const &array) {
    JULIA_XDIAG_CALL_RETURN(Permutation(array))
  });
  mod.method("con_Permutation", [](arma::Col<int64_t> const &array) {
    JULIA_XDIAG_CALL_RETURN(Permutation(array))
  });
  mod.method("con_Permutation", [](int64_t const *ptr, int64_t size) {
    JULIA_XDIAG_CALL_RETURN(Permutation(ptr, size))
  });
  mod.method("mth_size", [](const Permutation &self) {
    JULIA_XDIAG_CALL_RETURN(self.size())
  });
  mod.method("mth_inv", [](const Permutation &self) {
    JULIA_XDIAG_CALL_RETURN(self.inv())
  });
  mod.method("mth_array", [](const Permutation &self) {
    JULIA_XDIAG_CALL_RETURN(self.array())
  });
  mod.method("mth_operator*=", [](Permutation &self, Permutation const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self.operator*=(rhs))
  });
  mod.method("mth_operator==",
             [](Permutation const &self, Permutation const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
             });
  mod.method("mth_operator!=",
             [](Permutation const &self, Permutation const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator!=(rhs))
             });
  mod.method("fun_size",
             [](Permutation const &p) { JULIA_XDIAG_CALL_RETURN(size(p)) });
  mod.method("fun_multiply", [](Permutation const &p1, Permutation const &p2) {
    JULIA_XDIAG_CALL_RETURN(multiply(p1, p2))
  });
  mod.method("fun_operator*", [](Permutation const &p1, Permutation const &p2) {
    JULIA_XDIAG_CALL_RETURN(operator*(p1, p2))
  });
  mod.method("fun_inv",
             [](Permutation const &p) { JULIA_XDIAG_CALL_RETURN(inv(p)) });
  mod.method("fun_pow", [](Permutation const &p, int64_t power) {
    JULIA_XDIAG_CALL_RETURN(pow(p, power))
  });
  mod.method("fun_to_string", [](Permutation const &perm) {
    JULIA_XDIAG_CALL_RETURN(to_string(perm))
  });
  mod.method("con_PermutationGroup",
             []() { JULIA_XDIAG_CALL_RETURN(PermutationGroup()) });
  mod.method("con_PermutationGroup",
             [](std::vector<Permutation> const &permutations) {
               JULIA_XDIAG_CALL_RETURN(PermutationGroup(permutations))
             });
  mod.method("con_PermutationGroup", [](arma::Mat<int64_t> const &matrix) {
    JULIA_XDIAG_CALL_RETURN(PermutationGroup(matrix))
  });
  mod.method("con_PermutationGroup", [](int64_t *ptr, int64_t n_permutations,
                                        int64_t nsites) {
    JULIA_XDIAG_CALL_RETURN(PermutationGroup(ptr, n_permutations, nsites))
  });
  mod.method("mth_operator==",
             [](PermutationGroup const &self, PermutationGroup const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
             });
  mod.method("mth_operator!=",
             [](PermutationGroup const &self, PermutationGroup const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator!=(rhs))
             });
  mod.method("mth_size", [](const PermutationGroup &self) {
    JULIA_XDIAG_CALL_RETURN(self.size())
  });
  mod.method("mth_nsites", [](const PermutationGroup &self) {
    JULIA_XDIAG_CALL_RETURN(self.nsites())
  });
  mod.method("mth_ptr", [](PermutationGroup const &self, int64_t sym) {
    JULIA_XDIAG_CALL_RETURN(self.ptr(sym))
  });
  mod.method("mth_inv", [](PermutationGroup const &self, int64_t sym) {
    JULIA_XDIAG_CALL_RETURN(self.inv(sym))
  });
  mod.method("mth_multiply",
             [](PermutationGroup const &self, int64_t s1, int64_t s2) {
               JULIA_XDIAG_CALL_RETURN(self.multiply(s1, s2))
             });
  mod.method("mth_begin", [](const PermutationGroup &self) {
    JULIA_XDIAG_CALL_RETURN(self.begin())
  });
  mod.method("mth_end", [](const PermutationGroup &self) {
    JULIA_XDIAG_CALL_RETURN(self.end())
  });
  mod.method("fun_nsites", [](PermutationGroup const &group) {
    JULIA_XDIAG_CALL_RETURN(nsites(group))
  });
  mod.method("fun_size", [](PermutationGroup const &group) {
    JULIA_XDIAG_CALL_RETURN(size(group))
  });
  mod.method("fun_subgroup", [](PermutationGroup const &group,
                                std::vector<int64_t> const &symmetries) {
    JULIA_XDIAG_CALL_RETURN(subgroup(group, symmetries))
  });
  mod.method("fun_to_string", [](PermutationGroup const &group) {
    JULIA_XDIAG_CALL_RETURN(to_string(group))
  });
  mod.method("con_Representation",
             []() { JULIA_XDIAG_CALL_RETURN(Representation()) });
  mod.method("con_Representation", [](PermutationGroup const &group) {
    JULIA_XDIAG_CALL_RETURN(Representation(group))
  });
  mod.method("con_Representation",
             [](PermutationGroup const &group, Vector const &characters) {
               JULIA_XDIAG_CALL_RETURN(Representation(group, characters))
             });
  mod.method("con_Representation", [](std::string type, int64_t charge) {
    JULIA_XDIAG_CALL_RETURN(Representation(type, charge))
  });
  mod.method("mth_operator==",
             [](Representation const &self, Representation const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator==(rhs))
             });
  mod.method("mth_operator!=",
             [](Representation const &self, Representation const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self.operator!=(rhs))
             });
  mod.method("mth_is_permutation", [](const Representation &self) {
    JULIA_XDIAG_CALL_RETURN(self.is_permutation())
  });
  mod.method("mth_is_charge", [](const Representation &self) {
    JULIA_XDIAG_CALL_RETURN(self.is_charge())
  });
  mod.method("mth_isreal", [](const Representation &self) {
    JULIA_XDIAG_CALL_RETURN(self.isreal())
  });
  mod.method("mth_type", [](const Representation &self) {
    JULIA_XDIAG_CALL_RETURN(self.type())
  });
  mod.method("mth_group", [](const Representation &self) {
    JULIA_XDIAG_CALL_RETURN(self.group())
  });
  mod.method("mth_charge", [](const Representation &self) {
    JULIA_XDIAG_CALL_RETURN(self.charge())
  });
  mod.method("mth_characters", [](const Representation &self) {
    JULIA_XDIAG_CALL_RETURN(self.characters())
  });
  mod.method("fun_isreal", [](Representation const &irrep) {
    JULIA_XDIAG_CALL_RETURN(isreal(irrep))
  });
  mod.method("fun_isapprox", [](Representation const &r1,
                                Representation const &r2, double tol = 1e-12) {
    JULIA_XDIAG_CALL_RETURN(isapprox(r1, r2, 1e-12))
  });
  mod.method("fun_multiply",
             [](Representation const &r1, Representation const &r2) {
               JULIA_XDIAG_CALL_RETURN(multiply(r1, r2))
             });
  mod.method("fun_operator*",
             [](Representation const &r1, Representation const &r2) {
               JULIA_XDIAG_CALL_RETURN(operator*(r1, r2))
             });
  mod.method("fun_to_string", [](Representation const &irrep) {
    JULIA_XDIAG_CALL_RETURN(to_string(irrep))
  });
}
} // namespace xdiag::julia
