// GENERATED by model_sketch -- DO NOT EDIT.
#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {
void define_symmetries(jlcxx::Module &mod) {
  using namespace xdiag;
  mod.method("con_Permutation",
             []() { JULIA_XDIAG_CALL_RETURN(Permutation()) });
  mod.method("con_Permutation",
             [](int64_t size) { JULIA_XDIAG_CALL_RETURN(Permutation(size)) });
  mod.method("con_Permutation", [](arma::Col<int64_t> const &array) {
    JULIA_XDIAG_CALL_RETURN(Permutation(array))
  });
  mod.method("mth_size", [](Permutation const &self) {
    JULIA_XDIAG_CALL_RETURN(self.size())
  });
  mod.method("op_getindex", [](Permutation const &self, int64_t i) {
    JULIA_XDIAG_CALL_RETURN(self[i])
  });
  mod.method("mth_inv", [](Permutation const &self) {
    JULIA_XDIAG_CALL_RETURN(self.inv())
  });
  mod.method("op_eq", [](Permutation const &self, Permutation const &rhs) {
    JULIA_XDIAG_CALL_RETURN(self == rhs)
  });
  mod.method("fun_size",
             [](Permutation const &p) { JULIA_XDIAG_CALL_RETURN(size(p)) });
  mod.method("fun_multiply", [](Permutation const &p1, Permutation const &p2) {
    JULIA_XDIAG_CALL_RETURN(multiply(p1, p2))
  });
  mod.method("op_mul", [](Permutation const &p1, Permutation const &p2) {
    JULIA_XDIAG_CALL_RETURN(p1 * p2)
  });
  mod.method("fun_inv",
             [](Permutation const &p) { JULIA_XDIAG_CALL_RETURN(inv(p)) });
  mod.method("fun_pow", [](Permutation const &p, int64_t power) {
    JULIA_XDIAG_CALL_RETURN(pow(p, power))
  });
  mod.method("fun_to_string", [](Permutation const &perm) {
    JULIA_XDIAG_CALL_RETURN(to_string(perm))
  });
  mod.method("con_PermutationGroup",
             []() { JULIA_XDIAG_CALL_RETURN(PermutationGroup()) });
  mod.method("con_PermutationGroup", [](arma::Mat<int64_t> const &matrix) {
    JULIA_XDIAG_CALL_RETURN(PermutationGroup(matrix))
  });
  mod.method("op_eq",
             [](PermutationGroup const &self, PermutationGroup const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self == rhs)
             });
  mod.method("mth_size", [](PermutationGroup const &self) {
    JULIA_XDIAG_CALL_RETURN(self.size())
  });
  mod.method("mth_nsites", [](PermutationGroup const &self) {
    JULIA_XDIAG_CALL_RETURN(self.nsites())
  });
  mod.method("op_getindex", [](PermutationGroup const &self, int64_t sym) {
    JULIA_XDIAG_CALL_RETURN(self[sym])
  });
  mod.method("mth_inv", [](PermutationGroup const &self, int64_t sym) {
    JULIA_XDIAG_CALL_RETURN(self.inv(sym))
  });
  mod.method("mth_multiply",
             [](PermutationGroup const &self, int64_t s1, int64_t s2) {
               JULIA_XDIAG_CALL_RETURN(self.multiply(s1, s2))
             });
  mod.method("fun_nsites", [](PermutationGroup const &group) {
    JULIA_XDIAG_CALL_RETURN(nsites(group))
  });
  mod.method("fun_size", [](PermutationGroup const &group) {
    JULIA_XDIAG_CALL_RETURN(size(group))
  });
  mod.method("fun_to_string", [](PermutationGroup const &group) {
    JULIA_XDIAG_CALL_RETURN(to_string(group))
  });
  mod.method("con_Representation",
             []() { JULIA_XDIAG_CALL_RETURN(Representation()) });
  mod.method("con_Representation", [](PermutationGroup const &group) {
    JULIA_XDIAG_CALL_RETURN(Representation(group))
  });
  mod.method("con_Representation",
             [](PermutationGroup const &group, arma::vec const &characters) {
               JULIA_XDIAG_CALL_RETURN(Representation(group, characters))
             });
  mod.method("con_Representation",
             [](PermutationGroup const &group, arma::cx_vec const &characters) {
               JULIA_XDIAG_CALL_RETURN(Representation(group, characters))
             });
  mod.method("con_Representation", [](std::string const &type, int64_t charge) {
    JULIA_XDIAG_CALL_RETURN(Representation(type, charge))
  });
  mod.method("op_eq",
             [](Representation const &self, Representation const &rhs) {
               JULIA_XDIAG_CALL_RETURN(self == rhs)
             });
  mod.method("mth_is_permutation", [](Representation const &self) {
    JULIA_XDIAG_CALL_RETURN(self.is_permutation())
  });
  mod.method("mth_is_charge", [](Representation const &self) {
    JULIA_XDIAG_CALL_RETURN(self.is_charge())
  });
  mod.method("mth_isreal", [](Representation const &self) {
    JULIA_XDIAG_CALL_RETURN(self.isreal())
  });
  mod.method("mth_type", [](Representation const &self) {
    JULIA_XDIAG_CALL_RETURN(self.type())
  });
  mod.method("mth_group", [](Representation const &self) {
    JULIA_XDIAG_CALL_RETURN(self.group())
  });
  mod.method("mth_charge", [](Representation const &self) {
    JULIA_XDIAG_CALL_RETURN(self.charge())
  });
  mod.method("fun_isreal", [](Representation const &irrep) {
    JULIA_XDIAG_CALL_RETURN(isreal(irrep))
  });
  mod.method("fun_isapprox",
             [](Representation const &r1, Representation const &r2,
                double tol) { JULIA_XDIAG_CALL_RETURN(isapprox(r1, r2, tol)) });
  mod.method("fun_multiply",
             [](Representation const &r1, Representation const &r2) {
               JULIA_XDIAG_CALL_RETURN(multiply(r1, r2))
             });
  mod.method("op_mul", [](Representation const &r1, Representation const &r2) {
    JULIA_XDIAG_CALL_RETURN(r1 * r2)
  });
  mod.method("fun_to_string", [](Representation const &irrep) {
    JULIA_XDIAG_CALL_RETURN(to_string(irrep))
  });
  mod.method("fun_cyclic_group",
             [](int64_t n) { JULIA_XDIAG_CALL_RETURN(cyclic_group(n)) });
  mod.method("fun_cyclic_group_irrep", [](int64_t n, int64_t k) {
    JULIA_XDIAG_CALL_RETURN(cyclic_group_irrep(n, k))
  });
}
} // namespace xdiag::julia
