// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_types.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {

void define_types(jlcxx::Module &mod) {
  using namespace xdiag;
  mod.add_type<Boson>("typ_Boson");
  mod.add_type<BosonIterator>("typ_BosonIterator");
  mod.add_type<Electron>("typ_Electron");
  mod.add_type<ElectronIterator>("typ_ElectronIterator");
  mod.add_type<Fermion>("typ_Fermion");
  mod.add_type<FermionIterator>("typ_FermionIterator");
  mod.add_type<Spinhalf>("typ_Spinhalf");
  mod.add_type<SpinhalfIterator>("typ_SpinhalfIterator");
  mod.add_type<tJ>("typ_tJ");
  mod.add_type<tJIterator>("typ_tJIterator");
  mod.add_type<FileToml>("typ_FileToml");
  mod.add_type<FileTomlHandler>("typ_FileTomlHandler");
  mod.add_type<EigsLanczosResult>("typ_EigsLanczosResult");
  mod.add_type<EigvalsLanczosResult>("typ_EigvalsLanczosResult");
  mod.add_type<EigsLobpcgResult>("typ_EigsLobpcgResult");
  mod.add_type<EvolveLanczosResult>("typ_EvolveLanczosResult");
  mod.add_type<EvolveLanczosInplaceResult>("typ_EvolveLanczosInplaceResult");
  mod.add_type<TimeEvolveExpokitResult>("typ_TimeEvolveExpokitResult");
  mod.add_type<TimeEvolveExpokitInplaceResult>(
      "typ_TimeEvolveExpokitInplaceResult");
  mod.add_type<Monomial>("typ_Monomial");
  mod.add_type<Op>("typ_Op");
  mod.add_type<OpSum>("typ_OpSum");
  mod.add_type<ProductState>("typ_ProductState");
  mod.add_type<RandomState>("typ_RandomState");
  mod.add_type<State>("typ_State");
  mod.add_type<Permutation>("typ_Permutation");
  mod.add_type<PermutationGroup>("typ_PermutationGroup");
  mod.add_type<Representation>("typ_Representation");
  mod.add_type<COOMatrix<int32_t, double>>("typ_COOMatrix_int32_t_double");
  mod.add_type<COOMatrix<int32_t, complex>>("typ_COOMatrix_int32_t_complex");
  mod.add_type<COOMatrix<int64_t, double>>("typ_COOMatrix_int64_t_double");
  mod.add_type<COOMatrix<int64_t, complex>>("typ_COOMatrix_int64_t_complex");
  mod.add_type<CSRMatrix<int32_t, double>>("typ_CSRMatrix_int32_t_double");
  mod.add_type<CSRMatrix<int32_t, complex>>("typ_CSRMatrix_int32_t_complex");
  mod.add_type<CSRMatrix<int64_t, double>>("typ_CSRMatrix_int64_t_double");
  mod.add_type<CSRMatrix<int64_t, complex>>("typ_CSRMatrix_int64_t_complex");
  mod.add_type<CSCMatrix<int32_t, double>>("typ_CSCMatrix_int32_t_double");
  mod.add_type<CSCMatrix<int32_t, complex>>("typ_CSCMatrix_int32_t_complex");
  mod.add_type<CSCMatrix<int64_t, double>>("typ_CSCMatrix_int64_t_double");
  mod.add_type<CSCMatrix<int64_t, complex>>("typ_CSCMatrix_int64_t_complex");
}
} // namespace xdiag::julia
