// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_types.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {

void define_types(jlcxx::Module &mod) {
using namespace xdiag;
mod.add_type<Boson>("typ_Boson");
mod.add_type<BosonIterator>("typ_BosonIterator");
mod.add_type<Electron>("typ_Electron");
mod.add_type<ElectronIterator>("typ_ElectronIterator");
mod.add_type<Fermion>("typ_Fermion");
mod.add_type<FermionIterator>("typ_FermionIterator");
mod.add_type<Spinhalf>("typ_Spinhalf");
mod.add_type<SpinhalfIterator>("typ_SpinhalfIterator");
mod.add_type<tJ>("typ_tJ");
mod.add_type<tJIterator>("typ_tJIterator");
mod.add_type<FileToml>("typ_FileToml");
mod.add_type<FileTomlHandler>("typ_FileTomlHandler");
mod.add_type<Monomial>("typ_Monomial");
mod.add_type<Op>("typ_Op");
mod.add_type<OpSum>("typ_OpSum");
mod.add_type<ProductState>("typ_ProductState");
mod.add_type<RandomState>("typ_RandomState");
mod.add_type<State>("typ_State");
mod.add_type<Permutation>("typ_Permutation");
mod.add_type<PermutationGroup>("typ_PermutationGroup");
mod.add_type<Representation>("typ_Representation");
}

} // namespace xdiag::julia
