// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen/create_wrapper.sh -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>

namespace xdiag::julia {
void define_types(jlcxx::Module &mod);
}
