// GENERATED by model_sketch -- DO NOT EDIT.
#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {
void define_utils(jlcxx::Module &mod) {
  using namespace xdiag;
  mod.method("con_Error", [](std::string const &message,
                             std::string const &original_message) {
    JULIA_XDIAG_CALL_RETURN(Error(message, original_message))
  });
  mod.method("con_Error", [](Error const &error, std::string const &message) {
    JULIA_XDIAG_CALL_RETURN(Error(error, message))
  });
  mod.method("mth_original_message", [](Error const &self) {
    JULIA_XDIAG_CALL_RETURN(self.original_message())
  });
  mod.method("fun_error_trace", [](Error const &error) {
    JULIA_XDIAG_CALL_VOID(error_trace(error));
  });
  mod.method("fun_set_verbosity", [](int64_t level) {
    JULIA_XDIAG_CALL_VOID(set_verbosity(level));
  });
  mod.method("fun_version_string",
             []() { JULIA_XDIAG_CALL_RETURN(version_string()) });
  mod.method("fun_say_hello", []() { JULIA_XDIAG_CALL_VOID(say_hello()); });
  mod.method("fun_print_version",
             []() { JULIA_XDIAG_CALL_VOID(print_version()); });
}
} // namespace xdiag::julia
