// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_submodule.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {
void define_utils(jlcxx::Module &mod) {
  using namespace xdiag;
  mod.method("fun_throw_error", [](std::string message, const char *file,
                                   const char *func, int line) {
    JULIA_XDIAG_CALL_VOID(throw_error(message, file, func, line));
  });
  mod.method("fun_set_verbosity", [](int64_t level) {
    JULIA_XDIAG_CALL_VOID(set_verbosity(level));
  });
  mod.method("fun_version_string",
             []() { JULIA_XDIAG_CALL_RETURN(version_string()) });
  mod.method("fun_say_hello", []() { JULIA_XDIAG_CALL_VOID(say_hello()); });
  mod.method("fun_print_version",
             []() { JULIA_XDIAG_CALL_VOID(print_version()); });
  mod.method("fun_tic",
             [](bool begin = true, std::string msg = "", int verbosity = 0) {
               JULIA_XDIAG_CALL_VOID(tic(true, "", 0));
             });
  mod.method("fun_toc", [](std::string msg = "", int verbosity = 0) {
    JULIA_XDIAG_CALL_VOID(toc("", 0));
  });
}
} // namespace xdiag::julia
