// GENERATED by model_sketch/emit_module.py -- DO NOT EDIT.
#pragma once
#include "jlcxx/array.hpp"
#include "jlcxx/const_array.hpp"
#include "jlcxx/jlcxx.hpp"
#include "jlcxx/stl.hpp"
#include "jlcxx/tuple.hpp"
#include <cstdint>
#include <julia/src/armadillo.hpp>
#include <julia/src/sparse_algebra.hpp>
#include <xdiag/all.hpp>
using namespace xdiag;

// Plain structs must not be auto-mirrored by CxxWrap: we add_type them.
namespace jlcxx {
template <> struct IsMirroredType<EigsLanczosResult> : std::false_type {};
template <> struct IsMirroredType<EigvalsLanczosResult> : std::false_type {};
template <> struct IsMirroredType<EigsLobpcgResult> : std::false_type {};
template <> struct IsMirroredType<EvolveLanczosResult> : std::false_type {};
template <>
struct IsMirroredType<EvolveLanczosInplaceResult> : std::false_type {};
template <> struct IsMirroredType<TimeEvolveExpokitResult> : std::false_type {};
template <>
struct IsMirroredType<TimeEvolveExpokitInplaceResult> : std::false_type {};
} // namespace jlcxx

#define JULIA_XDIAG_CALL_VOID(CMD)                                             \
  try {                                                                        \
    CMD;                                                                       \
  } catch (xdiag::Error const &e) {                                            \
    xdiag::error_trace(e);                                                     \
    throw(std::runtime_error("Error occurred in XDiag C++ core library"));     \
  }
#define JULIA_XDIAG_CALL_RETURN(CMD)                                           \
  try {                                                                        \
    return CMD;                                                                \
  } catch (xdiag::Error const &e) {                                            \
    xdiag::error_trace(e);                                                     \
    throw(std::runtime_error("Error occurred in XDiag C++ core library"));     \
  }

namespace xdiag::julia {
void define_types(jlcxx::Module &mod);
void define_algebra(jlcxx::Module &mod);
void define_apply(jlcxx::Module &mod);
void define_blocks(jlcxx::Module &mod);
void define_io(jlcxx::Module &mod);
void define_kernels(jlcxx::Module &mod);
void define_linalg(jlcxx::Module &mod);
void define_matrix(jlcxx::Module &mod);
void define_operators(jlcxx::Module &mod);
void define_sparse(jlcxx::Module &mod);
void define_states(jlcxx::Module &mod);
void define_symmetries(jlcxx::Module &mod);
void define_utils(jlcxx::Module &mod);
} // namespace xdiag::julia
