// GENERATED by model_sketch/emit_module.py -- DO NOT EDIT.
#include <julia/src/xdiagjl.hpp>

JLCXX_MODULE define_julia_module(jlcxx::Module &mod) {
  using namespace xdiag;
  julia::define_armadillo(mod);
  julia::define_types(mod);
  julia::define_sparse_algebra(mod); // CSRMatrix types viewed by the algorithms
  julia::define_algebra(mod);
  julia::define_apply(mod);
  julia::define_blocks(mod);
  julia::define_io(mod);
  julia::define_kernels(mod);
  julia::define_linalg(mod);
  julia::define_matrix(mod);
  julia::define_operators(mod);
  julia::define_sparse(mod);
  julia::define_states(mod);
  julia::define_symmetries(mod);
  julia::define_utils(mod);
}
