# SPDX-FileCopyrightText: 2025 Alexander Wietek <awietek@pks.mpg.de>
#
# SPDX-License-Identifier: Apache-2.0

site_name: XDiag Documentation
theme:
  name: material
  palette:
    scheme: default
    primary: black
    accent: indigo
  features:
    - content.code.copy

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      auto_title: false
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - javascripts/katex.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css

nav:
  - Home: index.md
  - Quick Start: quick_start.md
  - User Guide:
    - user_guide/index.md
    - Installation: user_guide/01-installation.md
    - Writing code: user_guide/02-application.md
    - Hilbert spaces: user_guide/03-hilbert-spaces.md
    - Operators: user_guide/04-operators.md
    - States: user_guide/05-states.md
    - Dense matrices: user_guide/06-dense.md
    - Diagonalization: user_guide/07-diagonalization.md
    - Time evolution: user_guide/08-time-evolution.md
    - Measurements: user_guide/09-measurements.md
    - Input/Output: user_guide/10-io.md
    - Symmetries: user_guide/11-symmetries.md
    - Sparse matrices: user_guide/12-sparse.md
    - Distributed computing: user_guide/13-distributed.md
  - Examples: examples.md
  - Documentation: documentation/index.md
  - Benchmarks: benchmarks.md
  - Publications: publications.md
  - Contributing: contributing.md
  - Releases: releases.md
  - Citation: citation.md
  - About: about.md

hooks:
  - hooks/bibliography.py

plugins:
  - search
  - section-index