--- # Code
Code: QuantumLibrary/EDSLEngineIETL
gitversion: b2d7082de3f4fd9a366311cd0cdbb30d25ecaee5
host: n08-020
starttime: Mon Jan 22 15:22:31 2018
--- # Parameters
BandLanczos: 1
BandWidth: 6
BondmatrixFile: "/home/lv70545/awietek2/projekte/honeycomb.gamma/bondmatrices/bondmatrices.kitaevgamma.SU.2"
G: 0
HilbertspaceType: "HILBERTSPACE_2_TYPE"
J: 0
K: 1
LatticeDescriptionFile: "/home/lv70545/awietek2/projekte/honeycomb.gamma/lattice-files/honeycomb.32.HeisenbergKitaevGamma.fsl.lat"
MaxIterations: 10000
Nevals: 6
OutFile: "/home/lv70545/awietek2/projekte/honeycomb.gamma/outfiles/outfile.honeycomb.32.HB.Kitaev.Gamma.J.0.K.1.00000000000000000000.G.0.phi.0.0.k.Gamma.C2.B"
representation: "Gamma.C2.B"
sites: 32
--- # Results
Eigenvalue[0]=-6.2298697662279707288 (1)times
Eigenvalue[1]=-6.2276395195397595828 (1)times
Eigenvalue[2]=-6.2276395195397196147 (1)times
Eigenvalue[3]=-6.2276395195395872761 (1)times
Eigenvalue[4]=-6.216057350491118072 (1)times
Eigenvalue[5]=-6.2160573504880600737 (1)times
--- # Runtime
Lanczos steps for convergence (precision 9.9999999999999997989e-13): 1307
endtime: Mon Jan 22 18:01:24 2018
runtime: 9532.9838368892669678 secs
