#!/bin/bash

n_sites=8

t=1.
U=4.
outfile="out"
latticefile="/mnt/home/awietek/Research/Software/hydra/misc/lattice-files/chain.$n_sites.hubbard.hop.pbc"
nup=$(( $n_sites / 2 ))
ndown=$(( $n_sites / 2 ))
fermiontype="cdn"

/mnt/home/awietek/Research/Software/hydra/bin/hubbarddynamics \
--t $t \
--U $U \
--latticefile $latticefile \
--fermiontype $fermiontype \
--outfile $outfile \
--nup $nup \
--ndown $ndown \
