Opt std::string latfile "" l latfile latfile "name of lattice file"
Opt double J 1 j J J "J"
Opt double Jd 1 d Jd Jd "Jd"
Opt int nup 0 n nup nup "number of upspins"
Opt std::string k 0 k k k "space group irrep"
Opt std::string q 0 q q q "momentum q of spin operator"
Opt int seed 1 s seed seed "random seed"
Opt int niter 200 i niter niter "number of Lanczos iterations"
Opt std::string outfile "" o outfile outfile "name of outfile"
Opt std::string dumpdir "" v dumpdir dumpdir "name of dumpdir"
