Opt std::string outfile "" o outfile outfile "name of outfile"
Opt std::string latticefile "" l latticefile latticefile "name of latticefile"
Opt std::string couplingfile "" i couplingfile couplingfile "name of couplingfile (default: latticefile)"
Opt std::string corrfile "" c corrfile corrfile "name of file containing sites of correlator (optional: default empty, only 0-0 correlator is computed)"
Opt int nup -1 u nup nup "number of up electrons (optional, default half filling)"
Opt int ndown -1 d ndown ndown "number of down electrons (optional, default half filling)"
Opt std::string fermiontype "" f fermiontype fermiontype "type of fermion (one of cdagdn, cdn) (optinal: default all are computed)"
Opt std::string algorithm "" a algorithm algorithm "algorithm used (one of lanczos, bandlanczos) (default: lanczos)"
Opt int dyniters 200 d dyniters dyniters "number of dynamical Lanczos iterations performed (optional, default 200)"
