all:
	g++ -std=c++17 entanglement.cpp -o entanglement -framework Accelerate -litensor -L/Users/awietek/Research/Software/ITensor/lib -I/Users/awietek/Research/Software/itensor -lhydra -L/Users/awietek/Research/Software/hydra/lib -I/Users/awietek/Research/Software/hydra -I/Users/awietek/Research/Software/lila -DLILA_USE_ACCELERATE
