#!/bin/bash

project_root="/Users/awietek/Research/Software/xdiag"
generated_dir="/Users/awietek/Research/Software/xdiag/misc/wrapgen2/generated/cpp"

mkdir -p $generated_dir

# Create types.hpp and cpp
cat > "$generated_dir/types.hpp" <<EOF
// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen/create_wrapper.sh -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>

namespace xdiag::julia {
void define_types(jlcxx::Module &mod);
}
EOF

./code/emit_types_cpp.py > "$generated_dir/types.cpp"

julia_sources_file=julia_sources.cmake
echo "set(XDIAG_JULIA_SOURCES" > $generated_dir/$julia_sources_file
echo "    src/xdiagjl.cpp" >> $generated_dir/$julia_sources_file
echo "    src/types.cpp" >> $generated_dir/$julia_sources_file
echo "    src/modules.cpp" >> $generated_dir/$julia_sources_file


# Create modules.hpp and the cpp files
cat > "$generated_dir/modules.hpp" <<EOF
// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen/create_wrapper.sh -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>

namespace xdiag::julia {

void define_modules(jlcxx::Module & mod);

EOF

cat > "$generated_dir/modules.cpp" <<EOF
// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen/create_wrapper.sh -- DO NOT EDIT.

#include "modules.hpp"

namespace xdiag::julia {

void define_modules(jlcxx::Module & mod) {
EOF

modules=`ls -d $project_root/xdiag/*/ | sed "s|$project_root/xdiag/||" | sed "s|/||"`

for module in ${modules[@]}; do
    echo "void define_$module(jlcxx::Module &mod);" >> "$generated_dir/modules.hpp"
    echo "define_$module(mod);" >> "$generated_dir/modules.cpp"
    
    echo $module
    target=$generated_dir/$module.cpp
    ./code/emit_submodule_cpp.py $module > $target
    clang-format -i $target
    echo "    src/$module.cpp" >> $generated_dir/$julia_sources_file
done

echo ")" >> $generated_dir/$julia_sources_file
echo "}" >> "$generated_dir/modules.hpp"
echo "} }" >> "$generated_dir/modules.cpp"

./code/emit_xdiag_jl_hpp.py > $generated_dir/xdiagjl.hpp
./code/emit_xdiag_jl_cpp.py > $generated_dir/xdiagjl.cpp

clang-format -i $generated_dir/modules.hpp
clang-format -i $generated_dir/modules.cpp
clang-format -i $generated_dir/xdiagjl.hpp
clang-format -i $generated_dir/xdiagjl.cpp
clang-format -i $generated_dir/types.hpp
clang-format -i $generated_dir/types.cpp


