#!/bin/bash

project_root="/Users/awietek/Research/Software/xdiag"
generated_dir="/Users/awietek/Research/Software/xdiag/misc/wrapgen2/generated"

# Create types.hpp and cpp
cat > "$generated_dir/types.hpp" <<EOF
// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen/create_wrapper.sh -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>

namespace xdiag::julia {
void define_types(jlcxx::Module &mod);
}
EOF

./emit_types.py > "$generated_dir/types.cpp"
echo "set(XDIAG_JULIA_SOURCES" > $generated_dir/xdiag_julia_sources.cmake
echo "    src/types.cpp" >> $generated_dir/xdiag_julia_sources.cmake


# Create modules.hpp and the cpp files
cat > "$generated_dir/modules.hpp" <<EOF
// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen/create_wrapper.sh -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>

namespace xdiag::julia {
EOF

modules=`ls -d $project_root/xdiag/*/ | sed "s|$project_root/xdiag/||" | sed "s|/||"`

for module in ${modules[@]}; do

    echo "void define_$module(jlcxx::Module &mod);" >> "$generated_dir/modules.hpp"
    
    echo $module
    target=$generated_dir/$module.cpp
    ./emit_submodule.py $module > $target
    if clang-format -i $target; then
	echo "clang-format successful"
    else
	echo "clang-format failed"
    fi

    echo "    src/$module.cpp" >> $generated_dir/xdiag_julia_sources.cmake

done

echo "}" >> "$generated_dir/modules.hpp"
echo ")" >> $generated_dir/xdiag_julia_sources.cmake



