#!/usr/bin/env python

def emit_types():
    total_string = ""
    class_names = []
    with open("api.txt", "r") as fl:
        for line in [l for l in fl.readlines() if "CLASS_DECL" in l]:
            # class name comes directly after XDIAG_API
            spt = line.split(" ")
            idx = spt.index("XDIAG_API")
            class_names.append(str(spt[idx+1]))
            assert str(spt[idx+2]) == "{"
            
    header = """// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_types.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {

void define_types(jlcxx::Module &mod) {
using namespace xdiag;
"""
    total_string += header
    
    for class_name in class_names:
        cxx_class_name = "typ_" + class_name
        total_string += "mod.add_type<{}>(\"{}\");\n".format(
            class_name, cxx_class_name)

    footer = """}

} // namespace xdiag::julia"""
    total_string += footer
    return total_string

print(emit_types())
