#!/usr/bin/env python
import sys

ignored = ["operator<<", "operator++", "operator[]", "fill", "what"]
ignored_classes = ["FileTomlHandler", "GPWF"]

def is_deleted(line):
    return line.split("=")[-1].strip() == "delete"
def is_const_qualified(line):
    return line.split(")")[-1].strip() == "const"


def get_class_name(line):
    return str(line.split("[")[1].split("]")[0]).strip()

def get_args(line):
    args = str(line.split("(")[1].split(")")[0])
    args_raw = ", ".join([s.split(" ")[-1].replace("&", "").replace("*", "") for s in args.split(",")])
    return args, args_raw

def get_name_return_type(line, apitype):
    method_name = line.split("(")[0].split(" ")[-1].strip()
    return_type = " ".join(line.split(apitype)[1].split("(")[0].split(" ")[:-1]).strip()

    # correct for reference
    if method_name[0] == "&":
        method_name = method_name[1:]
        return_type += "&"

    # correct for pointer
    if method_name[0] == "*":
        method_name = method_name[1:]
        return_type += "*"
    return method_name, return_type
        
def emit_submodule(module):
    total_string = ""
    header = """// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_submodule.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>
"""
    total_string += header



    module_lines = []
    is_module_line = False
    total_header = "=== xdiag"
    module_header = "=== xdiag/{}".format(module)

    headers = []

    with open("api.txt", "r") as fl:
        for line in fl.readlines():
            if is_module_line:
                if total_header in line and module_header not in line:
                    is_module_line = False
                    break
                module_lines.append(str(line).strip())
                
            else:   # !is_module_line
                if module_header in line:
                    is_module_line = True

    for header in headers:
        total_string += header
        
    header = """
namespace xdiag::julia {{
void define_{0}(jlcxx::Module &mod) {{
using namespace xdiag;
""".format(module)
    total_string += header                

    for line in module_lines:

        if is_deleted(line):
            continue
        
        ss = "" 

        if "CONSTRUCTOR" in line:
            class_name = get_class_name(line)
            
            if class_name in ignored_classes:
                continue
            
            args, args_raw = get_args(line)
            ss += "mod.method(\"con_{}\", []({}) {{ ".format(class_name, args)
            ss += "  JULIA_XDIAG_CALL_RETURN({}({})) ".format(class_name, args_raw);
            ss += "});\n"

        elif "CXX_METHOD" in line:
            class_name = get_class_name(line)
            args, args_raw = get_args(line)
            method_name, return_type = get_name_return_type(line, "CXX_METHOD")
            if method_name in ignored:
                continue

            conststr = "const" if is_const_qualified(line) else ""
            
            
            if args == "":
                ss += "mod.method(\"mth_{}\", []({} {}& self) {{ ".format(method_name, conststr, class_name)
            else:
                ss += "mod.method(\"mth_{}\", []({} {}& self, {}) {{ ".format(method_name, class_name, conststr, args)

            if return_type == "void":
                ss += "JULIA_XDIAG_CALL_VOID(self.{}({})); ".format(method_name, args_raw);
            else:
                ss += "JULIA_XDIAG_CALL_RETURN(self.{}({}))".format(method_name, args_raw);
            ss += "});\n"

        elif "FUNCTION_DECL" in line:
            args, args_raw = get_args(line)
            function_name, return_type = get_name_return_type(line, "FUNCTION_DECL")

            if function_name in ignored:
                continue
            
            ss += "mod.method(\"fun_{}\", []({}) {{ ".format(function_name, args)
            if return_type == "void":
                ss += "JULIA_XDIAG_CALL_VOID({}({})); ".format(function_name, args_raw);
            else:
                ss += "JULIA_XDIAG_CALL_RETURN({}({}))".format(function_name, args_raw);
            ss += "});\n"

            
            # print("{:20s} {:20s} {:20s} {:20s}".format(function_name, return_type, args, args_raw))
        total_string += ss
        

            
    
    footer = """}
} // namespace xdiag::julia"""
    total_string += footer
    return total_string

module = str(sys.argv[1])
print(emit_submodule(module))
