# SPDX-License-Identifier: Apache-2.0
#
# Shared output plumbing for the C++/Julia emitters: file banners, the
# .method() registration helper, and the file writers.

from pathlib import Path

OUT = Path(__file__).with_name("out")

CPP_HEADER = ("// GENERATED by model_sketch -- DO NOT EDIT.\n"
              "#include <julia/src/xdiagjl.hpp>\n#include <xdiag/all.hpp>\n\n"
              "namespace xdiag::julia {{\nvoid define_{0}(jlcxx::Module &mod) {{\n"
              "using namespace xdiag;\n")
CPP_FOOTER = "}\n} // namespace xdiag::julia\n"
JL_HEADER = "# GENERATED by model_sketch -- DO NOT EDIT.\n\n"


def register_method(abi_name, params, call_expr, is_void):
    """One CxxWrap `mod.method(...)` registration line whose lambda forwards to
    the wrapped C++ call (guarded by the stack-trace-preserving macros)."""
    body = (f"JULIA_XDIAG_CALL_VOID({call_expr});" if is_void
            else f"JULIA_XDIAG_CALL_RETURN({call_expr})")
    return f'mod.method("{abi_name}", []({", ".join(params)}) {{ {body} }});'


def write_cpp(name, lines):
    (OUT / "cpp").mkdir(parents=True, exist_ok=True)
    (OUT / "cpp" / f"{name}.cpp").write_text(
        CPP_HEADER.format(name) + "\n".join(lines) + "\n" + CPP_FOOTER)


def write_jl(name, lines):
    (OUT / "julia").mkdir(parents=True, exist_ok=True)
    (OUT / "julia" / f"{name}.jl").write_text(JL_HEADER + "\n".join(lines) + "\n")
