#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
#
# Emit the top-level wiring, after the per-module files exist:
#   out/cpp/xdiagjl.hpp  -- shared header: macros, IsMirroredType, define_ decls
#   out/cpp/xdiagjl.cpp  -- JLCXX_MODULE entry point registering every module
#   out/julia/XDiag.jl   -- the Julia module: @wrapmodule, includes, exports
# The armadillo bridge is a static module wired in first.

import apidb
import emitutil
import overrides
import typetable as T
from emit_submodule import BASE, LINALG, wrappable

OUT = emitutil.OUT
SPECIAL = {"types", "armadillo", "sparse_algebra", "xdiagjl", "XDiag"}   # not auto-listed

HPP = """// GENERATED by model_sketch/emit_module.py -- DO NOT EDIT.
#pragma once
#include <cstdint>
#include "jlcxx/array.hpp"
#include "jlcxx/const_array.hpp"
#include "jlcxx/jlcxx.hpp"
#include "jlcxx/stl.hpp"
#include "jlcxx/tuple.hpp"
#include <xdiag/all.hpp>
#include <julia/src/armadillo.hpp>
#include <julia/src/sparse_algebra.hpp>
using namespace xdiag;

// Plain structs must not be auto-mirrored by CxxWrap: we add_type them.
namespace jlcxx {{
{mirrored}
}}

#define JULIA_XDIAG_CALL_VOID(CMD)                                             \\
  try {{ CMD; }} catch (xdiag::Error const &e) {{                             \\
    xdiag::error_trace(e);                                                     \\
    throw(std::runtime_error("Error occurred in XDiag C++ core library"));     \\
  }}
#define JULIA_XDIAG_CALL_RETURN(CMD)                                           \\
  try {{ return CMD; }} catch (xdiag::Error const &e) {{                      \\
    xdiag::error_trace(e);                                                     \\
    throw(std::runtime_error("Error occurred in XDiag C++ core library"));     \\
  }}

namespace xdiag::julia {{
void define_types(jlcxx::Module &mod);
{decls}
}}
"""

CPP = """// GENERATED by model_sketch/emit_module.py -- DO NOT EDIT.
#include <julia/src/xdiagjl.hpp>

JLCXX_MODULE define_julia_module(jlcxx::Module &mod) {{
  using namespace xdiag;
  julia::define_armadillo(mod);
  julia::define_types(mod);
  julia::define_sparse_algebra(mod);   // CSRMatrix types viewed by the algorithms
{calls}
}}
"""

JL = """# GENERATED by model_sketch/emit_module.py -- DO NOT EDIT.
module XDiag

using CxxWrap
using LinearAlgebra
using XDiag_jll
{linalg_import}
export {exports}

@wrapmodule(XDiag_jll.get_libxdiagjl_path)

include("armadillo.jl")
include("types.jl")
include("sparse_algebra.jl")
{includes}

function __init__()
    @initcxx
end

end
"""


def submodules():
    return sorted(p.stem for p in (OUT / "cpp").glob("*.cpp") if p.stem not in SPECIAL)


def exported_names(entries):
    # both free functions and methods are ordinary Julia functions in the module
    callables = {e["name"] for e in entries
                 if e["kind"] in ("function", "method") and wrappable(e)[0]}
    names = {e["name"] for e in entries if e["kind"] in ("class", "struct")
             and e["name"] not in overrides.IGNORED_CLASSES}
    # LinearAlgebra functions we extend are re-exported (so `using XDiag` alone
    # provides dot/norm); Base functions stay unexported (Base is always in scope).
    linalg = sorted(n for n in callables if n in LINALG)
    for n in callables:
        merged_c = n.endswith("C") and n[:-1] in callables   # dotC etc. -> merged into dot
        if n not in BASE and not n.startswith("operator") and not merged_c:
            names.add(n)
    return sorted(names), linalg


def main():
    entries = apidb.load()
    T.register_classes(e["name"] for e in entries if e["kind"] in ("class", "struct")
                       and e["name"] not in overrides.IGNORED_CLASSES)
    T.register_result_structs(e["name"] for e in entries if e.get("fields"))
    mods = submodules()
    # Julia-only static specials: a static .jl with no .cpp sibling is still
    # included (it registers no C++ methods, so it gets no define_ call).
    cpp_stems = {p.stem for p in (OUT / "cpp").glob("*.cpp")}
    jl_only = sorted(p.stem for p in (OUT / "julia").glob("*.jl")
                     if p.stem not in SPECIAL and p.stem not in cpp_stems)

    mirrored = "\n".join(
        f"template <> struct IsMirroredType<{e['name']}> : std::false_type {{}};"
        for e in entries if e["kind"] == "struct"
        and e["name"] not in overrides.IGNORED_CLASSES)
    decls = "\n".join(f"void define_{m}(jlcxx::Module &mod);" for m in mods)
    calls = "\n".join(f"  julia::define_{m}(mod);" for m in mods)
    includes = "\n".join(f'include("{m}.jl")' for m in [*mods, *jl_only])
    names, linalg = exported_names(entries)
    exports = ", ".join(names)
    linalg_import = f"import LinearAlgebra: {', '.join(linalg)}" if linalg else ""

    (OUT / "cpp" / "xdiagjl.hpp").write_text(HPP.format(mirrored=mirrored, decls=decls))
    (OUT / "cpp" / "xdiagjl.cpp").write_text(CPP.format(calls=calls))
    (OUT / "julia" / "XDiag.jl").write_text(
        JL.format(exports=exports, includes=includes, linalg_import=linalg_import))
    print(f"wired {len(mods)} modules -> xdiagjl.hpp, xdiagjl.cpp, XDiag.jl")


if __name__ == "__main__":
    main()
