#!/usr/bin/env python
from itertools import product
from common import *

def emit_types():
    total_string = ""
    class_names = []
    with open("api.txt", "r") as fl:
        for line in [l for l in fl.readlines() if "CLASS_DECL" in l or "STRUCT_DECL" in l]:
            class_names.append(get_class_name(line))
    with open("api.txt", "r") as fl:
        class_template_lines = [l for l in fl.readlines() if "CLASS_TEMPLATE" in l]

    header = """// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_types.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {

void define_types(jlcxx::Module &mod) {
using namespace xdiag;
"""
    total_string += header
    
    for class_name in class_names:
        cxx_class_name = "typ_" + class_name
        total_string += "mod.add_type<{}>(\"{}\");\n".format(
            class_name, cxx_class_name)

    # Walk through class templates and create instantiations
    # (should be exclusively the sparse matrix types)
    for l in class_template_lines:
        basename, args = class_template_basename_args(l)
        instantiations = class_template_instantiations[basename]
        combos = list(product(*instantiations.values()))        
        for combo in combos:
            class_name, cxx_class_name = class_template_name(basename, combo)
            total_string += "mod.add_type<{}>(\"{}\");\n".format(
            class_name, cxx_class_name)

    footer = """}
} // namespace xdiag::julia"""
    total_string += footer

    return total_string

print(emit_types())
