#!/usr/bin/env python
import sys
from common import *
        
def emit_submodule(module):
    ts = ""
    header = """// SPDX-License-Identifier: Apache-2.0
// GENERATED by misc/wrapgen2/emit_submodule.py -- DO NOT EDIT.

#include <julia/src/xdiagjl.hpp>
#include <xdiag/all.hpp>

namespace xdiag::julia {{
void define_{0}(jlcxx::Module &mod) {{
using namespace xdiag;
""".format(module)
    ts += header                

    module_lines = get_module_lines("api.txt", module)
    for line in module_lines:
        if is_deleted(line):
            continue
        
        ss = "" 

        if "CONSTRUCTOR" in line:
            class_name = get_parent_class_name(line)
            if class_name in ignored_classes:
                continue
            
            args, args_raw = get_args(line)

            # the block constructors with RepresentationSet will not be exposed to Julia
            if "RepresentationSet" in args:
                continue

            args_all = get_substituted_args(args)
            for arg in args_all:
                ss += "mod.method(\"con_{}\", []({}) {{ ".format(class_name, arg)
                ss += "  JULIA_XDIAG_CALL_RETURN({}({})) ".format(class_name, args_raw);
                ss += "});\n"

        elif "CXX_METHOD" in line:
            class_name = get_parent_class_name(line)
            method_name, return_type = get_name_return_type(line, "CXX_METHOD")
            args, args_raw = get_args(line)
            args_all = get_substituted_args(args)
                            
            if method_name in ignored_methods or return_type in ignored_types:
                continue
            conststr = "const" if is_const_qualified(line) else ""           
            
            for args in args_all:
                if args == "":
                    ss += "mod.method(\"mth_{}\", []({} {}& self) {{ ".format(method_name, conststr, class_name)
                else:
                    ss += "mod.method(\"mth_{}\", []({} {}& self, {}) {{ ".format(method_name, class_name, conststr, args)
                    
                if return_type == "void":
                    ss += "JULIA_XDIAG_CALL_VOID(self.{}({})); ".format(method_name, args_raw);
                else:
                    ss += "JULIA_XDIAG_CALL_RETURN(self.{}({}))".format(method_name, args_raw);
                ss += "});\n"

        elif "FUNCTION_DECL" in line:
            function_name, return_type = get_name_return_type(line, "FUNCTION_DECL")
            if function_name in ignored_methods or return_type in ignored_types:
                continue
            args, args_raw = get_args(line)
            args_all = get_substituted_args(args)
                       
            for args in args_all:
                ss += "mod.method(\"fun_{}\", []({}) {{ ".format(function_name, args)
                if return_type == "void":
                    ss += "JULIA_XDIAG_CALL_VOID({}({})); ".format(function_name, args_raw);
                else:
                    ss += "JULIA_XDIAG_CALL_RETURN({}({}))".format(function_name, args_raw);
                ss += "});\n"

        elif "STRUCT_DECL" in line:
            struct_name, fields = get_struct_name_fields(line)
            for field in fields:
                ss += "mod.method(\"mth_{}\", []({} const& self) {{ ".format(
                    field, struct_name)
                ss += "return self.{}; }});\n".format(field);

        ts += ss

    # Finally, operator overloads
    ts += "\n// operator overloads \n"
    for line in module_lines:

        if "CXX_METHOD" in line:
            class_name = get_parent_class_name(line)
            method_name, return_type = get_name_return_type(line, "CXX_METHOD")
           
            # operator[] get's special treatment
            if(method_name == "operator[]"):
                # Ignore all weird return types except "Scalar"
                if return_type in ignored_types and not "Scalar" in return_type:
                    continue                    
                
                args, args_raw = get_args(line)
                if (is_const_qualified(line)):   # read access
                    if "Scalar" not in return_type:  

                        ts += "mod.method(\"op_getindex\", []({} const& self, {}) {{ ".format(class_name, args)
                        ts += "JULIA_XDIAG_CALL_RETURN(self[{}])".format(args_raw)
                        ts += "});\n"
                else:                             # write access
                    raw_return_type = decay_type(return_type)
                    if raw_return_type == "Scalar":
                        types = ["double", "complex"]
                    else:
                        types = [raw_return_type]
                    for typ in types:
                        ts += "mod.method(\"op_setindex\", []({}& self, {}, {} const& val) {{ ".format(class_name, args, typ)
                        ts += "JULIA_XDIAG_CALL_VOID(self[{}] = val);".format(args_raw)
                        ts += "});\n"
                continue
            

            if decay_type(return_type) not in julia_types.keys() or\
               return_type in ignored_types:
                continue
            
            if contains_invalid_type(line):
                continue
            
            if method_name not in operator_aux_julia_name.keys():
                continue

            conststr = "const" if is_const_qualified(line) else ""           
            args, args_raw = get_args(line)
            aux_method_name, _ = operator_aux_julia_name[method_name]
            if args == "":
                ts += "mod.method(\"op_{}\", []({} {}& self) {{ ".format(
                    aux_method_name, conststr, class_name)
            else:
                ts += "mod.method(\"op_{}\", []({} {}& self, {}) {{ ".format(
                    aux_method_name, class_name, conststr, args)
                    
            if return_type == "void":
                ts += "JULIA_XDIAG_CALL_VOID(self.{}({})); ".format(
                    method_name, args_raw);
            else:
                ts += "JULIA_XDIAG_CALL_RETURN(self.{}({}))".format(
                    method_name, args_raw);

            ts += "});\n"

        elif "FUNCTION_DECL" in line:
            function_name, return_type = get_name_return_type(line, "FUNCTION_DECL")
            if return_type not in julia_types.keys() or\
               return_type in ignored_types:
                continue

            if function_name not in operator_aux_julia_name.keys():
                continue

            if contains_invalid_type(line):
                continue
            
            args, args_raw = get_args(line)
            args_all = get_substituted_args(args)
            aux_function_name, _ = operator_aux_julia_name[function_name]

            ts += "mod.method(\"op_{}\", []({}) {{ ".format(
                aux_function_name, args)
            if return_type == "void":
                ts += "JULIA_XDIAG_CALL_VOID({}({})); ".format(
                    function_name, args_raw);
            else:
                ts += "JULIA_XDIAG_CALL_RETURN({}({}))".format(
                    function_name, args_raw);
                
            ts += "});\n"
            
    footer = """}
} // namespace xdiag::julia"""
    ts += footer
    return ts

module = str(sys.argv[1])
# emit_submodule(module)
print(emit_submodule(module))
