Opt std::string outfile "" o outfile outfile "name of outfile"
Opt std::string latticefile "" l latticefile latticefile "name of latticefile"
Opt std::string couplingfile "" t couplingfile couplingfile "name of couplingfile"
Opt std::string corrfile "" c corrfile corrfile "name of file describing the current operator"
Opt std::string corrcouplingfile "" c corrcouplingfile corrcouplingfile "name of file describing the current operator couplilngs"
Opt std::string method "" m method method "method to use (FTLM, Sym0, SymR)"
Opt int nup -1 u nup nup "number of up electrons (optional, default half filling)"
Opt int ndown -1 d ndown ndown "number of down electrons (optional, default half filling)"
Opt int iters 100 i iters iters "maximum number of ground state Lanczos iterations performed (optional, default 1000)"
Opt int verbosity 1 v verbosity verbosity "verbosity level, one of 0, 1 ,2 (optional, default 1)"
Opt int seed 1 s seed seed "random seed"
