// SPDX-FileCopyrightText: 2026 Alexander Wietek <awietek@pks.mpg.de>
//
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include <cstdint>
#include <initializer_list>
#include <string>
#include <vector>

#include <xdiag/operators/coeff.hpp>
#include <xdiag/operators/op.hpp>

namespace xdiag {

// Monomial represents an ordered product of elementary operators (Ops).
// It is the monomial element of the free associative algebra generated by Op.
//
// Products are formed by concatenation - no simplification or reordering is
// performed automatically. Use logic/order.hpp and logic/collect.hpp to
// canonicalize and combine equal monomials.
//
// A single Op implicitly converts to a length-1 Monomial, so all OpSum
// construction that previously used (Coeff, Op) pairs continues to work.
class XDIAG_API Monomial {
public:
  Monomial() = default;
  Monomial(Op const &op);                  // implicit single-op
  Monomial(std::initializer_list<Op> ops); // Monomial{A, B, C}
  explicit Monomial(std::vector<Op> const &ops);

  int64_t size() const noexcept;
  bool empty() const noexcept;
  Op const &operator[](int64_t idx) const;
  std::vector<Op> const &ops() const noexcept;

  using iterator_t = std::vector<Op>::const_iterator;
  iterator_t begin() const noexcept;
  iterator_t end() const noexcept;

  // Algebra product (free algebra): concatenation, no simplification
  Monomial operator*(Op const &rhs) const;
  Monomial operator*(Monomial const &rhs) const;
  Monomial &operator*=(Op const &rhs);
  Monomial &operator*=(Monomial const &rhs);

  bool operator==(Monomial const &rhs) const noexcept;
  bool operator!=(Monomial const &rhs) const noexcept;
  bool operator<(Monomial const &rhs) const noexcept; // lexicographic

  // Hermitian conjugation is provided by hc() (operators/hc.hpp), which returns
  // an OpSum so it can carry a phase (e.g. hc(ExchangeAsym) = -ExchangeAsym).
  bool isreal() const;

private:
  std::vector<Op> ops_;
};

// Free-function algebra products: Op * Op and Op * Monomial
XDIAG_API Monomial operator*(Op const &lhs, Op const &rhs);
XDIAG_API Monomial operator*(Op const &lhs, Monomial const &rhs);

XDIAG_API bool isreal(Monomial const &m);
XDIAG_API std::ostream &operator<<(std::ostream &out, Monomial const &m);
XDIAG_API std::string to_string(Monomial const &m);

// Term = one summand in an OpSum: a coefficient times an ordered product of Ops
struct Term {
  Coeff coeff;
  Monomial monomial;
  bool operator==(Term const &rhs) const noexcept;
  bool operator!=(Term const &rhs) const noexcept;
};

} // namespace xdiag
