// SPDX-FileCopyrightText: 2026 Alexander Wietek <awietek@pks.mpg.de>
//
// SPDX-License-Identifier: Apache-2.0

#pragma once

#include <cstdint>
#include <initializer_list>
#include <string>
#include <vector>

#include <xdiag/operators/coeff.hpp>
#include <xdiag/operators/op.hpp>

namespace xdiag {

// Monomial represents an ordered product of elementary operators (Ops).
// It is the monomial element of the free associative algebra generated by Op.
//
// Products are formed by concatenation — no simplification or reordering is
// performed automatically. Use logic/order.hpp and logic/collect.hpp to
// canonicalize and combine equal monomials.
//
// A single Op implicitly converts to a length-1 Monomial, so all OpSum
// construction that previously used (Coeff, Op) pairs continues to work.
class Monomial {
public:
  XDIAG_API Monomial() = default;
  XDIAG_API Monomial(Op const &op);                  // implicit single-op
  XDIAG_API Monomial(std::initializer_list<Op> ops); // Monomial{A, B, C}
  XDIAG_API explicit Monomial(std::vector<Op> const &ops);

  XDIAG_API int64_t size() const noexcept;
  XDIAG_API bool empty() const noexcept;
  XDIAG_API Op const &operator[](int64_t idx) const;
  XDIAG_API std::vector<Op> const &ops() const noexcept;

  using iterator_t = std::vector<Op>::const_iterator;
  XDIAG_API iterator_t begin() const noexcept;
  XDIAG_API iterator_t end() const noexcept;

  // Algebra product (free algebra): concatenation, no simplification
  XDIAG_API Monomial operator*(Op const &rhs) const;
  XDIAG_API Monomial operator*(Monomial const &rhs) const;
  XDIAG_API Monomial &operator*=(Op const &rhs);
  XDIAG_API Monomial &operator*=(Monomial const &rhs);

  XDIAG_API bool operator==(Monomial const &rhs) const noexcept;
  XDIAG_API bool operator!=(Monomial const &rhs) const noexcept;
  XDIAG_API bool operator<(Monomial const &rhs) const noexcept; // lexicographic

  // Hermitian conjugation is provided by hc() (operators/hc.hpp), which returns
  // an OpSum so it can carry a phase (e.g. hc(ExchangeAsym) = -ExchangeAsym).
  XDIAG_API bool isreal() const;

private:
  std::vector<Op> ops_;
};

// Free-function algebra products: Op * Op and Op * Monomial
XDIAG_API Monomial operator*(Op const &lhs, Op const &rhs);
XDIAG_API Monomial operator*(Op const &lhs, Monomial const &rhs);

XDIAG_API bool isreal(Monomial const &m);
XDIAG_API std::ostream &operator<<(std::ostream &out, Monomial const &m);
XDIAG_API std::string to_string(Monomial const &m);

// Term = one summand in an OpSum: a coefficient times an ordered product of Ops
struct Term {
  Coeff coeff;
  Monomial monomial;
  XDIAG_API bool operator==(Term const &rhs) const noexcept;
  XDIAG_API bool operator!=(Term const &rhs) const noexcept;
};

} // namespace xdiag
