Opt std::string outfile "" o outfile outfile "name of outfile"
Opt std::string latticefile "" l latticefile latticefile "name of latticefile"
Opt std::string couplingfile "" t couplingfile couplingfile "name of couplingfile"
Opt int nup -1 u nup nup "number of up electrons (optional, default half filling)"
Opt int ndown -1 d ndown ndown "number of down electrons (optional, default half filling)"
Opt double precision 1e-12 p precision precision "precision to converge (optional, default 1e-12)"
Opt int neigenvalue 0 n neigenvalue neigenvalue "which eigenvalue to converge (optional, default 0)"
Opt int iters 1000 i iters iters "maximum number of ground state Lanczos iterations performed (optional, default 1000)"
Opt int verbosity 1 v verbosity verbosity "verbosity level, one of 0, 1 ,2 (optional, default 1)"
Opt int seed 1 s seed seed "random seed"
Opt bool measure_kinetic false k measure_kinetic measure_kinetic "measure_kinetic"
