Opt std::string outfile "" o outfile outfile "name of outfile"
Opt std::string latticefile "" l latticefile latticefile "name of latticefile"
Opt std::string couplingfile "" t couplingfile couplingfile "name of couplingfile (default: latticefile)"
Opt std::string corrfile "" c corrfile corrfile "name of file describing the current operator"
Opt int nup -1 u nup nup "number of up electrons (optional, default half filling)"
Opt int ndown -1 d ndown ndown "number of down electrons (optional, default half filling)"
Opt double precision 1e-12 p precision precision "precision of ground state Lanczos procedure (optional, default 1e-12)"
Opt int iters 1000 i iters iters "maximum number of ground state Lanczos iterations performed (optional, default 1000)"
Opt double dynprecision 1e-12 q dynprecision dynprecision "precision of dynamical Lanczos procedure (optional, default 1e-12)"
Opt int dyniters 1000 j dyniters dyniters "maximum number of dynamical Lanczos iterations performed (optional, default 1000)"
Opt int verbosity 1 v verbosity verbosity "verbosity level, one of 0, 1 ,2 (optional, default 1)"
Opt int lobpcgbands 1 b lobpcgbands lobpcgbands "number of lobpcg bands for ground state search"
Opt int seed 0 s seed seed "random seed"
Opt double temperature 0 T temperature temperature "temperature to evaluate TPQ state, if 0, ground state is computed"