set(XDIAG_SOURCES
  utils/iochecks.cpp
  utils/error.cpp
  utils/logger.cpp
  utils/say_hello.cpp
  utils/read_vectors.cpp
  utils/split.cpp
  utils/timing.cpp
  
  io/read.cpp
  io/file_toml.cpp
  io/file_h5.cpp
  io/toml/file_toml_handler.cpp
  io/toml/value.cpp
  io/toml/std_vector.cpp
  io/toml/arma_vector.cpp
  io/toml/arma_matrix.cpp
  io/toml/operators.cpp
  io/hdf5/file_h5_handler.cpp
  io/hdf5/file_h5_subview.cpp
  io/hdf5/utils.cpp
  io/hdf5/write.cpp
  io/hdf5/types.cpp
  
  math/ipow.cpp
  math/binomial.cpp
  math/scalar.cpp
  math/vector.cpp
  math/matrix.cpp
  math/arma_to_cx.cpp
  math/dot.cpp
  math/norm.cpp
  math/isapprox.cpp
  
  matrices/apply.cpp
  matrices/matrix.cpp
  matrices/sparse/coo_matrix.cpp
  matrices/sparse/csr_matrix.cpp
  matrices/sparse/csc_matrix.cpp
  matrices/sparse/valid.cpp
  matrices/sparse/apply.cpp
  matrices/blocks/spinhalf/kernels.cpp
  matrices/blocks/boson/kernels.cpp
  matrices/blocks/fermion/kernels.cpp
  matrices/blocks/electron/kernels.cpp
  matrices/blocks/tj/kernels.cpp
  matrices/terms/non_branching_op.cpp
  matrices/terms/cdagc_string.cpp
  
  bits/bitset.cpp
  bits/bitvector.cpp
  bits/bitarray.cpp
  bits/pack_unpack.cpp
  bits/to_string.cpp
  
  combinatorics/combinations/enumerate_combinations.cpp
  combinatorics/combinations/combinations.cpp
  combinatorics/combinations/lin_table.cpp
  combinatorics/subsets/subsets.cpp
  combinatorics/bounded_multisets/bounded_multisets.cpp
  combinatorics/bounded_partitions/bounded_partitions.cpp
  combinatorics/bounded_partitions/count_bounded_partitions.cpp
  combinatorics/bounded_partitions/schaefer_table.cpp
  
  basis/basis.cpp
  basis/basis_onthefly.cpp
  basis/basis_electron.cpp
  basis/basis_electron_symmetric.cpp
  basis/basis_tj.cpp
  basis/basis_sublattice.cpp
  basis/basis_symmetric.cpp

  blocks/blocks.cpp
  blocks/print_block.cpp
  blocks/spinhalf.cpp
  blocks/boson.cpp
  blocks/fermion.cpp
  blocks/electron.cpp
  blocks/tj.cpp
  
  states/product_state.cpp
  states/random_state.cpp
  states/create_state.cpp
  states/state.cpp
  states/apply.cpp
  states/dot.cpp
  states/inner.cpp
  states/expect.cpp
  states/correlation_matrix.cpp
  states/norm.cpp
  states/fill.cpp
  
  random/random_utils.cpp
  random/hash.cpp
  
  operators/coeff.cpp
  operators/monomial.cpp
  operators/op.cpp
  operators/opsum.cpp
  operators/types.cpp
  operators/hc.cpp
  operators/valid.cpp
  operators/collect.cpp

  symmetries/permutation.cpp
  symmetries/permutation_group.cpp
  symmetries/representation.cpp
  symmetries/representation_set.cpp
  symmetries/cyclic_group.cpp
  symmetries/fermi_sign.cpp

  symmetries/action/site_permutation.cpp
  symmetries/action/isrepresentative.cpp
  symmetries/action/representative.cpp
  symmetries/action/norm.cpp
  symmetries/action/norm_fermionic.cpp
  symmetries/action/site_permutation_sublattice.cpp
  symmetries/action/sublattice_stability.cpp
  symmetries/tables/representative_table.cpp
  symmetries/tables/fermi_table.cpp

  algebra/symmetrize.cpp
  algebra/permute.cpp
  algebra/representation.cpp
  algebra/normal_order.cpp
  algebra/isapprox.cpp
  algebra/ishermitian.cpp

  algebra/algebras/algebra.cpp
  algebra/algebras/spin_algebra.cpp
  algebra/algebras/electron_algebra.cpp
  algebra/algebras/tj_algebra.cpp
  algebra/algebras/tj_implementation_algebra.cpp
  algebra/algebras/matrix_algebra.cpp
  algebra/algebras/spinhalf_implementation_algebra.cpp
  algebra/algebras/fermion_implementation_algebra.cpp
  algebra/algebras/fermion_algebra.cpp
  algebra/algebras/electron_implementation_algebra.cpp

  algebra/rewrite/rewrite.cpp
  algebra/rewrite/rules/id_absorption_rule.cpp
  algebra/rewrite/rules/sort_sites_rule.cpp
  algebra/rewrite/rules/spinhalf_same_site_rule.cpp
  algebra/rewrite/rules/electron_same_site_rule.cpp
  algebra/rewrite/rules/electron_normal_order_rule.cpp
  algebra/rewrite/rules/electron_protected_expansion_rule.cpp
  algebra/rewrite/rules/fermion_same_site_rule.cpp
  algebra/rewrite/rules/fermion_normal_order_rule.cpp
  algebra/rewrite/rules/tj_same_site_rule.cpp
  algebra/rewrite/rules/tj_protected_expansion_rule.cpp
  algebra/rewrite/rules/tj_normal_order_rule.cpp
  algebra/rewrite/rules/combine_matrix_rule.cpp
  algebra/rewrite/rules/sort_matrix_sites_rule.cpp
  algebra/rewrite/rules/spinhalf_sdots_rule.cpp
  algebra/rewrite/rules/convert_to_matrix_rule.cpp
  algebra/rewrite/rules/spin_expansion_rules.cpp
  algebra/rewrite/rules/electron_expansion_rules.cpp
  algebra/rewrite/rules/fermion_expansion_rules.cpp
  algebra/rewrite/rules/tj_expansion_rules.cpp
  algebra/rewrite/rules/boson_expansion_rules.cpp
  algebra/rewrite/rules/totaln_expansion_rule.cpp
  algebra/rewrite/rules/hubbardu_expansion_rule.cpp

  algebra/utils/combine_matrix_ops.cpp
  algebra/utils/permute_matrix_op.cpp
  algebra/utils/op_to_matrix_op.cpp
  algebra/utils/swap_pair.cpp
  algebra/utils/replace_pair.cpp
  algebra/utils/check_allowed_types.cpp
  
  linalg/lanczos/lanczos_convergence.cpp
  linalg/lanczos/tmatrix.cpp
  linalg/lanczos/eigvals_lanczos.cpp
  linalg/lanczos/eigs_lanczos.cpp
  linalg/sparse_diag.cpp
  linalg/arnoldi/arnoldi_to_disk.cpp
  linalg/gram_schmidt/gram_schmidt.cpp
  linalg/gram_schmidt/orthogonalize.cpp
  linalg/norm_estimate.cpp
  linalg/time_evolution/time_evolve.cpp
  linalg/time_evolution/imaginary_time_evolve.cpp
  linalg/time_evolution/time_evolve_expokit.cpp
  linalg/time_evolution/evolve_lanczos.cpp
  linalg/time_evolution/expm.cpp
)
set(XDIAG_DISTRIBUTED_SOURCES
  parallel/mpi/allreduce.cpp
  parallel/mpi/alltoall.cpp
  parallel/mpi/communicator.cpp
  parallel/mpi/comm_pattern.cpp
  parallel/mpi/datatype.cpp
  parallel/mpi/cdot_distributed.cpp
  parallel/mpi/timing_mpi.cpp
  parallel/mpi/buffer.cpp
  basis/spinhalf_distributed/basis_spinhalf_distributed.cpp
  basis/spinhalf_distributed/basis_sz.cpp
  basis/spinhalf_distributed/transpose.cpp
  basis/spinhalf_distributed/apply/apply_terms.cpp
  
  basis/tj_distributed/basis_tj_distributed.cpp
  basis/tj_distributed/basis_np.cpp
  basis/electron_distributed/basis_electron_distributed.cpp
  basis/electron_distributed/basis_np.cpp
  
  blocks/spinhalf_distributed.cpp
  blocks/tj_distributed.cpp
  blocks/electron_distributed.cpp
)
set(XDIAG_JULIA_SOURCES
  xdiagjl.cpp
  algebra/matrix.cpp
  algebra/apply.cpp
  algebra/algebra.cpp
  algebra/sparse/coo_matrix.cpp
  algebra/sparse/csr_matrix.cpp
  algebra/sparse/csc_matrix.cpp
  algebra/sparse/apply.cpp
  linalg/sparse_diag.cpp
  linalg/lanczos/eigs_lanczos.cpp
  linalg/lanczos/eigvals_lanczos.cpp
  linalg/time_evolution/time_evolve.cpp
  linalg/time_evolution/imaginary_time_evolve.cpp
  linalg/time_evolution/time_evolve_expokit.cpp  
  linalg/time_evolution/evolve_lanczos.cpp
  blocks/spinhalf.cpp
  blocks/tj.cpp
  blocks/electron.cpp
  io/file_toml.cpp
  io/read.cpp
  
  operators/op.cpp
  operators/opsum.cpp
  operators/symmetrize.cpp
  operators/hc.cpp
  operators/block.cpp
  
  states/create_state.cpp
  states/fill.cpp
  states/random_state.cpp
  states/product_state.cpp
  states/gpwf.cpp
  states/state.cpp
  utils/utils.cpp
  utils/armadillo.cpp
  symmetries/permutation.cpp
  symmetries/permutation_group.cpp
  symmetries/representation.cpp
  symmetries/u1.cpp
)
