Opt double T 0.1 t temperature temperature "temperature (ignored if temperaturefile is given)"
Opt double t 1. t t t "Hubbard t"
Opt double U 4. U U U "Hubbard U"
Opt std::string outfile "" o outfile outfile "name of outfile"
Opt std::string latticefile "" l latticefile latticefile "name of latticefile"
Opt std::string temperaturefile "" t temperaturefile temperaturefile "name of temperaturefile"
Opt int nup -1 u nup nup "number of up electrons (optional, default half filling)"
Opt int ndown -1 d ndown ndown "number of down electrons (optional, default half filling)"
Opt int np -1 p np np "number of particles (optional, default half filling)"
