Opt std::string outfile "" o outfile outfile "name of outfile"
Opt std::string latticefile "" l latticefile latticefile "name of latticefile"
Opt std::string couplingfile "" c couplingfile couplingfile "name of couplingfile (default: latticefile)"
Opt std::string evaluate "evaluate" e evaluate evaluate "choose whether to evaluate or not, either evaluate/notevaluate/onlyevaluate" 
Opt std::string method "exact" m method method "method to use, either exact or TPQ (default: exact)" 
Opt std::string temperaturefile "" t temperaturefile temperaturefile "name of temperaturefile"
Opt int seed 42 s seed seed "random seed (optional, default 42)"
Opt double precision 1e-12 p precision precision "precision of Lanczos procedure (optional, default 1e-12)"
Opt int neval 1 n neval neval "number of eigenvalue to converge (optional, default 1)"
Opt int iters 1000 i iters iters "maximum number of ground state Lanczos iterations performed (optional, default 1000)"
Opt int nup -1 u nup nup "number of up electrons (optional, default half filling)"
Opt int ndown -1 d ndown ndown "number of down electrons (optional, default half filling)"
Opt int np -1 p np np "number of particles (optional, default half filling)"
Flag loseevals l loseevals loseevals "flag whether eigenvalues should not be written to output"
