name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make test
      run: |
        git clone https://github.com/awietek/lila.git
        cp options.mk.sample options.mk
        liladir=`echo $PWD/lila`
        sed -i "s|/mnt/home/awietek/Research/Software/lila|$liladir|g" options.mk
        cat options.mk
        make
        make test
    - name: run tests
      run: |
        cd test
        ./tests