name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: lila
      run: git clone git@github.com:awietek/lila.git
    - name: options
      run: |
        cp options.mk.sample options.mk
        ls
    - name: make
      run: make
    - name: make test
      run: make test
