Opt std::string outfile "" o outfile outfile "name of outfile"
Opt std::string latticefile "" l latticefile latticefile "name of latticefile"
Opt std::string couplingfile "" t couplingfile couplingfile "name of couplingfile"
Opt int nup -1 u nup nup "number of up electrons (optional, default half filling)"
Opt int ndown -1 d ndown ndown "number of down electrons (optional, default half filling)"
Opt int verbosity 1 v verbosity verbosity "verbosity level, one of 0, 1 ,2 (optional, default 1)"
